(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.canada_big = function() {
	this.initialize(img.canada_big);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,243,241);


(lib.iihf_logo = function() {
	this.initialize(img.iihf_logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,76,109);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,144,43);


(lib.maska_01 = function() {
	this.initialize(img.maska_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,144,145);


(lib.maska_02 = function() {
	this.initialize(img.maska_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,145,145);


(lib.maska_03 = function() {
	this.initialize(img.maska_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,151,145);


(lib.maska_05 = function() {
	this.initialize(img.maska_05);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,146,157);


(lib.maska_06 = function() {
	this.initialize(img.maska_06);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,151,157);


(lib.maska_07 = function() {
	this.initialize(img.maska_07);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,143,156);


(lib.pole = function() {
	this.initialize(img.pole);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,400,184);


(lib.rus_big = function() {
	this.initialize(img.rus_big);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,230,227);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Символ53 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#0000FF").ss(1,1,1).p("Egx6gXvMBj1AAAMAAAAvfMhj1AAAg");
	this.shape.setTransform(319.5,152);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ53, new cjs.Rectangle(-1,-1,641,306), null);


(lib.Символ51 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0948B0").s().p("ACSCQQgTgEgOgIQgPgIgIgMQgKgLgDgPQgBgIAEgGQADgFAJgDIAogNQAKgEAFACQAFACACAIQAEAKAKAGQAKAFARABQAWAAAMgHQAMgFACgMQACgJgLgGQgKgFgYgDQgkgGgVgJQgPgHgJgLQgJgJgEgRQgEgRAEgWQADgUAKgPQALgQAQgKQARgLAWgGQAXgFAcAAQAWAAAQAEQAQAEAMAHQAMAHAIALQAIALAFAPQADAJgDAEQgCAEgKAEIgoAPQgIAEgEgCQgEgBgEgJQgDgLgJgFQgKgEgOAAQgTAAgLAEQgKAFgCALQgCALAMAFQAKAFAcAEQAUADAPAFQATAHANAKQAHAFAFAHQAFAHADAJQAEAJAAAMQABAMgDANQgEAVgKAQQgKAQgRAKQgRAKgXAGQgYAFgeAAQgWAAgTgEgAhuCQQgTgEgOgIQgOgIgJgMQgJgLgDgPQgBgIADgGQAEgFAJgDIAogNQAJgEAFACQAFACADAIQADAKALAGQAKAFARABQAVAAAMgHQAMgFACgMQACgJgLgGQgJgFgZgDQgkgGgUgJQgPgHgJgLQgJgJgEgRQgEgRADgWQAEgUAKgPQAKgQARgKQAQgLAXgGQAXgFAcAAQAUAAARAEQAQAEAMAHQAMAHAIALQAIALAFAPQACAJgCAEQgDAEgJAEIgoAPQgJAEgEgCQgEgBgDgJQgEgLgIgFQgJgEgPAAQgTAAgKAEQgLAFgBALQgCALAMAFQAJAFAdAEQAUADAOAFQATAHAMAKQAHAFAFAHQAGAHADAJQADAJABAMQAAAMgCANQgEAVgKAQQgLAQgRAKQgRAKgWAGQgXAFgeAAQgXAAgTgEgAlkCSQgNgCgKgEQgLgEgIgHQgJgFgGgJQgHgIgEgJQgFgJgCgLQgDgOADghIAcibQACgKAEgDQAFgEAJAAIAtAAQAKAAADAEQADADgCAKIgdClQgCAJABAHQACAHAEAFQAFAEAHACQAIADAKAAQAKAAAIgDQAJgCAFgEQAMgKADgSIAeilQABgKAFgDQAEgEAKAAIAtAAQAKAAADAEQADADgCAKIgeCoQgIAggHANQgRAYgMAIQgZAQgPAEQghAHgUAAgAKVCOQgPAAgGgEQgFgDgBgKIgEgcIhXAAIgOAcQgFAKgGADQgHAEgOAAIgsAAQgIAAgCgEQgCgEAFgIICIj9QAFgIAFgDQAEgDAJAAIAuAAQAJAAAEADQAEADACAIIAvD9QACAIgEAEQgEAEgJAAgAJvAiIgHgvQgCgZACgWIACgIIgEAAQgKAmgIARIgXAvIAyAAgAFeCOQgJAAgDgEQgDgDABgJIAtj7QACgJAEgDQAEgEAJAAIAvAAQAJAAADAEQACADgBAJIgsD7QgCAJgEADQgEAEgJAAgAoaCOQgQAAgHgFQgHgDgEgLIgQg3QgDgMgFgEQgFgEgMgBIgKAAIgOBOQgCAKgEADQgEAEgJAAIguAAQgJAAgEgEQgDgDACgKIAsj5QACgKAFgDQAEgEAJAAIByAAQAXAAARAHQASAHAKANQALANAEASQAEATgEAWQgDAOgFAMQgEALgHAJQgIALgJAHQgKAJgMAFIAIASIAYBFQADAIgEAFQgEAGgJAAgApjgSIArAAQAMAAAIgIQAJgHACgMQACgMgFgHQgGgHgNAAIgrAAg");
	this.shape.setTransform(71.8,14.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ51, new cjs.Rectangle(0,0,143.6,29.6), null);


(lib.Символ49 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AjNBfQgKgCgFgGQgKgLAFgfIAMhDIgZAAQgEAAAAgFIACgHQAAgEAFAAIAZAAIAEgbQABgFAFAAIAIAAQAFAAgBAFIgFAbIAmAAQAFAAgBAEIgCAHQgBAFgEAAIgmAAIgMBCQgBAMAAAHQABAIADADQADAEAHACQAHABALAAQAFAAgBAFIgBAHQgBAFgFAAIgEAAQgNAAgIgDgAJCBeQgKgEgGgHQgGgHgCgKQgBgKACgMIAGgiQACgMAGgKQAFgKAJgHQAJgGALgEQALgDAOAAQANAAAKADQAKADAHAGQAGAGACAJQACAIgCAKQgCAJgFAGQgEAHgIAFQgIAEgKACQgLACgNAAQgcgBgNgDIgCANQgCAJABAGQACAHAEAFQAEAEAHACQAHADAJAAQAPAAALgFQAKgFAIgLQAFgEADACIAFAEQAEACgDAFIgMAMQgGAFgIADQgHAEgJABQgIACgKAAQgOAAgKgEgAJggZQgIADgGAFQgGAFgEAHQgEAGgCAJIgCAKQAOADAcACQAJAAAHgCQAHgBAFgDQAFgDADgFQAEgEABgGQACgGgCgGQgBgFgEgEQgFgDgHgCQgHgCgKAAQgJAAgIACgAG2BgQgLgCgIgEQgGgDgCgCQgBgDABgGIAeipQABgEAFAAIAIAAQAFAAgBAEIgLA7IAYgGQALgCAIAAQANAAAJADQAJAEAFAGQAFAHACAKQABAJgCAMIgGAlQgDANgFAKQgFAKgIAGQgIAGgLAEQgMADgNAAQgOAAgKgCgAHTgZIgVAHIgQBYQgBAFAFACIANAEIAQABQAKAAAIgCQAIgDAFgEQAGgFAEgHQAEgHABgKIAHgkQABgIgBgHQgBgGgEgFQgDgEgHgCQgGgDgJAAQgJAAgKACgADxBeQgJgEgGgHQgGgHgCgKQgCgKACgMIAHgiQACgMAGgKQAFgKAJgHQAIgGALgEQAMgDAOAAQANAAAKADQAKADAGAGQAHAGACAJQACAIgCAKQgCAJgFAGQgFAHgHAFQgIAEgLACQgKACgOAAQgbgBgOgDIgCANQgBAJABAGQABAHAEAFQAEAEAHACQAHADAKAAQAOAAALgFQALgFAIgLQAEgEAEACIAFAEQAEACgEAFIgLAMQgHAFgHADQgIAEgIABQgJACgKAAQgOAAgKgEgAEPgZQgHADgGAFQgHAFgDAHQgFAGgBAJIgCAKQANADAcACQAJAAAHgCQAHgBAFgDQAGgDADgFQADgEACgGQABgGgBgGQgBgFgFgEQgEgDgHgCQgHgCgKAAQgKAAgIACgAARBeQgJgEgGgHQgFgHgCgKQgCgKACgMIAGgiQACgMAGgKQAFgKAJgHQAIgGALgEQAMgDAOAAQANAAAKADQAKADAGAGQAHAGACAJQACAIgCAKQgCAJgFAGQgFAHgHAFQgIAEgLACQgKACgOAAQgbgBgOgDIgCANQgBAJABAGQABAHAEAFQAEAEAHACQAHADAKAAQAOAAALgFQALgFAIgLQAEgEAEACIAFAEQAEACgEAFIgLAMQgHAFgHADQgIAEgIABQgJACgKAAQgOAAgKgEgAAvgZQgHADgGAFQgHAFgDAHQgFAGgBAJIgCAKQANADAcACQAJAAAHgCQAHgBAFgDQAGgDADgFQADgEACgGQABgGgBgGQgBgFgFgEQgEgDgHgCQgHgCgKAAQgKAAgIACgAB/BeQgFAAABgEIAThuQACgGACgDQACgDAGgCQALgEAMgCQAMgCAOAAIAIAAQAFAAgBAEIgBAHQgBAFgFAAIgbABIgRAEQgFACgBAFIgSBoQgBAEgEAAgAg6BeQgFAAABgEIAOhSQACgIgBgGQgCgHgDgEQgEgFgGgCQgHgCgJAAQgMAAgKACQgKACgIADIgTBtQgBAEgFAAIgIAAQgFAAABgEIAhi3QAAgEAFAAIAIAAQAFAAgBAEIgKA6QAJgEAKgBQAKgCANAAQANAAAJADQAJADAFAHQAGAHABAKQACAJgCAMIgPBRQgBAEgEAAgAllBeQgEAAAAgEIAgi3QACgEAEAAIAIAAQAFAAgBAEIggC3QgBAEgFAAgAmaBeQgFAAABgEIAgi3QABgEAFAAIAIAAQAFAAgBAEIghC3QgBAEgEAAgAnPBeQgFAAABgEIAWh8QABgEAFAAIAIAAQAFAAgBAEIgWB8QgBAEgFAAgAooBeQgFAAAAgEIgNh9IgBgZIgBAAQgDAMgGANIg6B9QgCAEgFAAIgIAAQgGAAAAgEIgQiuQAAgFAFAAIAKAAQAGAAAAAEIAKB9IAAAcIABAAIAKgcIA4h6QACgFAGAAIAIAAQAFAAABAFIANCWIABAAIBAiZQABgEAGAAIAKAAQAEAAgCAFIhMCuQgDAEgFAAgAmvhBQgGAAgBgCQgCgCABgGIAAgCQABgFADgCQACgCAGAAIABAAQAGAAABACQACACgBAFIAAACQgBAGgDACQgCACgGAAg");
	this.shape.setTransform(67.7,9.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ49, new cjs.Rectangle(0,0,135.4,19.6), null);


(lib.Символ48 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1956C9").s().p("AKKCFQgKgEgJgFQgIgGgGgIQgHgHgEgJQgFgIgCgKQgCgKAAgMIACgXIAMhEQADgRANgbIAMgRIAQgPQALgJAcgLQAPgEAkgDIAaACQAMACAKAEQAKAEAIAFQAJAGAGAIQAHAHAEAJQAEAJACAKQADAKAAALIgOBcQgIAfgIAMIgMASIgQAOQgYAPgPAFQggAHgTAAQgjgDgNgFgALMhHQgIACgGAFQgGAEgEAHQgEAHgCAJIgNBLQgBAIABAHQACAHAEAFQAFAEAHADQAIACAKAAQApAAAGgkIAOhLQABgJgBgHQgCgGgEgFQgFgFgHgCQgHgCgKAAQgLAAgIACgAg1CJQgSgEgOgIQgNgHgJgLQgIgLgDgPQgBgHADgFQAEgFAIgDIAmgNQAJgDAFABQAEACADAIQADAKAKAFQAKAFAQAAQATAAALgFQAMgGACgKQACgKgLgFQgIgFgXgDQgigFgTgJQgPgHgIgKQgJgJgEgPQgEgSAEgUQADgTAKgPQAJgOAQgKQAQgKAVgGQAVgFAbAAQAUAAAQAEQAPADALAIQAMAHAIAKQAHAKAFAOQACAJgCAEQgCAEgKADIglAPQgJADgDgBQgEgCgDgIQgEgKgJgFQgIgFgOAAQgSAAgJAFQgKAFgCAKQgCALAMAFQAIAEAbADQATADAOAFQASAGAMAKQAHAGAFAGQAFAHADAIQADAJAAALQABALgCANQgEAUgKAPQgKAOgQAKQgQAKgWAFQgWAGgcAAQgVAAgSgEgAk0CFQgKgEgJgFQgIgGgGgIQgHgHgEgJQgFgIgCgKQgCgKAAgMIACgXIAMhEQADgRANgbIAMgRIAQgPQALgJAcgLQAPgEAkgDIAaACQAMACAKAEQAKAEAIAFQAJAGAGAIQAHAHAEAJQAEAJACAKQADAKAAALIgOBcQgIAfgIAMIgMASIgQAOQgYAPgPAFQggAHgTAAQgjgDgNgFgAjyhHQgIACgGAFQgGAEgEAHQgEAHgCAJIgNBLQgBAIABAHQACAHAEAFQAFAEAHADQAIACAKAAQApAAAGgkIAOhLQABgJgBgHQgCgGgEgFQgFgFgHgCQgHgCgKAAQgLAAgIACgAwjCFQgKgEgJgFQgIgGgGgIQgHgHgEgJQgFgIgCgKQgCgKAAgMIACgXIAMhEQADgRANgbIAMgRIAQgPQALgJAcgLQAPgEAkgDIAaACQAMACAKAEQAKAEAIAFQAJAGAGAIQAHAHAEAJQAEAJACAKQADAKAAALIgOBcQgIAfgIAMIgMASIgQAOQgYAPgPAFQggAHgTAAQgjgDgNgFgAvhhHQgIACgGAFQgGAEgEAHQgEAHgCAJIgNBLQgBAIABAHQACAHAEAFQAFAEAHADQAIACAKAAQApAAAGgkIAOhLQABgJgBgHQgCgGgEgFQgFgFgHgCQgHgCgKAAQgLAAgIACgAPxCHQgKAAgEgIIgqhaQgIgQgEgTQgEgRgEgZIgDAAQADA2gHArIgLA+QgCAJgEADQgEAEgJAAIgoAAQgJAAgDgEQgDgDABgJIAqjtQACgJAEgEQAEgDAJAAIAsAAQAKAAAEAIIAtBhQANAjAHAhIADAAQgEgiAAgNQgBgOAFgiIALg+QACgJAEgEQAEgDAJAAIAoAAQAJAAADADQADAEgCAJIgqDtQgBAJgEADQgFAEgJAAgAHiCHQgJAAgCgDQgDgEABgIIAqjvQACgJAEgDQAEgDAIAAIAtAAQAJAAACADQADAEgBAIIgrDvQgBAIgEADQgEAEgIAAgAE3CHQgJAAgDgEQgDgDACgJIAhi7Ig4AAQgKAAgDgDQgCgEABgJIAGgiQACgJAEgEQAEgDAJAAIC8AAQAJAAAEADQADAEgCAJIgGAiQgCAJgEAEQgEADgJAAIg5AAIghC7QgCAJgEADQgEAEgJAAgACLCHQgIAAgDgDQgDgEACgIIAqjvQACgJAEgDQADgDAJAAIAtAAQAIAAADADQADAEgCAIIgqDvQgCAIgDADQgEAEgJAAgApfCHQgJAAgDgEQgDgDABgJIAqjtQACgJAEgEQAEgDAJAAIBpAAQAtAAAVAbQALAOAEATQADASgEAXQgDAVgKAQQgJARgPALQgOALgUAFQgSAGgYAAIguAAIgLBBQgCAJgEADQgEAEgJAAgAoKgMIAlAAQANAAAKgHQAIgIADgMQACgNgGgIQgHgIgNAAIglAAgAtVCHQgJAAgDgEQgDgDABgJIAqjtQACgJAEgEQAEgDAJAAIBpAAQAtAAAVAbQALAOAEATQADASgEAXQgDAVgKAQQgJARgPALQgOALgUAFQgSAGgYAAIguAAIgLBBQgCAJgEADQgEAEgJAAgAsAgMIAlAAQANAAAKgHQAIgIADgMQACgNgGgIQgHgIgNAAIglAAg");
	this.shape.setTransform(111.3,14.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ48, new cjs.Rectangle(0,0,222.6,28.2), null);


(lib.Символ47 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D22D27").s().p("AsbCUQgjgqAMhDIAQhbQAEgWAQglIARgXIAUgTQAQgLAmgPQAUgGAxgDQAbAAAWAGQAWAGAQALQAQAMAKARQALAQAEAXQADAMgEAGQgEAGgNAEIg0AQQgMADgGgDQgFgCgCgMQgEgQgMgHQgMgIgUAAQgPAAgLADQgLADgIAHQgIAGgFAKQgFAKgDAOIgQBcQgCANABAKQACAKAFAHQAGAGAKADQAKAEAPAAQAaAAAQgJQAQgKADgQIACgKIgxAAQgMAAgEgFQgEgEACgNIAHglQACgMAGgFQAFgFAMAAICBAAQAMAAAEAFQADAFgBAMIgNBJQgFAcgOAWQgOAWgXAQQgXAQgeAIQgrAIgZAAQhKAAgigpgAJIC1QgMAAgEgEQgEgFACgMIAtj7IhMAAQgMAAgEgEQgEgFACgNIAIgtQADgNAFgEQAGgFALAAID9AAQAMAAAEAFQAEAFgCAMIgIAtQgCANgGAFQgFAEgNAAIhLAAIgtD7QgCAMgGAFQgFAEgMAAgAGPC1QgSAAgHgEQgIgFgBgMIgFglIhuAAIgSAlQgHAMgIAFQgIAEgSAAIg4AAQgLAAgCgFQgDgFAGgLICvlCQAFgLAGgDQAGgEAMAAIA6AAQALAAAFAEQAGAEACAJIA8FDQACALgEAFQgFAFgLAAgAFfArIgIg7QgDghADgbIABgLIgEAAQgNAwgKAXIgdA7IA/AAgAiNC1QgNAAgEgEQgEgFADgMIA4k+QADgNAFgEQAFgFAMAAIDVAAQAMAAAFAFQADAFgBAMIgJAtQgBANgGAFQgGAEgMAAIiGAAIgIAuIBrAAQAMAAAEAFQADAEgCAMIgIAtQgDANgFAEQgFAFgMAAIhrAAIgIAxICKAAQAMAAADAFQAEAEgCANIgIAuQgCAMgGAFQgFAEgMAAgAkOC1QgTAAgKgFQgJgGgEgNIgVhGQgFgQgFgFQgHgFgPAAIgNAAIgRBjQgDAMgFAFQgGAEgMAAIg5AAQgNAAgEgEQgEgFADgMIA4k+QADgNAFgEQAFgFAMAAICSAAQAdAAAWAJQAWAJAOAQQAOARAEAXQAFAYgFAdQgDASgGAPQgHAOgIAMQgKANgMAKQgMAKgPAIIAKAWIAeBXQAEALgFAHQgFAHgMAAgAlrgXIA3AAQAQAAAKgJQALgKACgQQADgPgHgJQgHgJgQAAIg3AAg");
	this.shape.setTransform(82.2,18.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ47, new cjs.Rectangle(0,0,164.4,37.8), null);


(lib.Символ46 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0044B2").s().p("AJfBzQgGAAACgGIAbiZQABgFACgDQACgDAGgCQAKgEALgBQAMgCANAAQAMAAAJADQAJADAFAHQAFAGACAJQABAKgCALIgGAhQgCAMgFAJQgEAJgIAGQgHAGgKADQgKADgNAAIgOgCIgQgFIgJAyQgBAGgGAAgAKOgpQgEACAAADIgOBMQALAEASACQAHAAAHgCQAGgCAEgDQAFgEADgGQADgFABgIIAGgfQABgIgBgFQgBgGgDgDQgEgEgFgCQgGgCgIAAQgNAAgNAEgAiHBzQgGAAACgGIAbiZQABgFACgDQACgDAGgCQAKgEALgBQAMgCANAAQAMAAAJADQAJADAFAHQAFAGACAJQABAKgCALIgGAhQgCAMgFAJQgEAJgIAGQgHAGgKADQgKADgNAAIgOgCIgQgFIgJAyQgBAGgGAAgAhYgpQgEACAAADIgOBMQALAEASACQAHAAAHgCQAGgCAEgDQAFgEADgGQADgFABgIIAGgfQABgIgBgFQgBgGgDgDQgEgEgFgCQgGgCgIAAQgNAAgNAEgAFRBAQgIgCgGgDQgGgEgEgGQgEgFgCgIQgBgFAGgCIAJgDQAFgCACAFQADAKAHAEQAHAEANAAIANgCQAGgBAEgCQAEgCADgEQACgDABgFQABgFgBgDQgCgDgDgCQgGgEgSgCQgXgDgIgFQgHgEgCgHQgDgHACgLQABgJAEgHQAFgGAGgFQAHgEAKgDQAJgCAMAAQAKAAAHABQAIACAFADQAGADAEAFQADAFACAHQACAGgGACIgIADQgDACgCgBQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQgDgIgHgEQgHgEgMAAQgNAAgIAFQgIAEgBAJQgBAGACAEQACAEAHACQAEABAPACQALABAHACQAIACAGADQAGAEACAIQADAHgCAKQgCAJgEAHQgEAGgIAFQgHAFgKACQgKADgMAAQgKAAgIgCgABPA/QgKgEgGgGQgGgGgCgIQgCgJACgLIAHgmQABgKAGgJQAFgIAIgGQAIgGAKgDQALgDAMAAQANAAAJADQAKADAGAHQAGAGACAIQACAJgCALIgHAmQgCALgEAIQgFAIgIAGQgIAGgLADQgKADgNAAQgNAAgJgDgABqgrQgGACgFADQgFAEgDAFQgDAEgBAHIgHAmQgBAGABAFQACAFADADQAEAEAGACQAFABAIAAQAHAAAHgBQAGgCAFgEQAFgDADgFQADgFABgGIAHgmQABgHgBgEQgCgFgDgEQgEgDgGgCQgFgCgIAAQgHAAgHACgAmsA+QgJgDgFgHQgFgHgBgJQgCgKACgLIAGghQACgMAFgJQAFgJAHgFQAHgGALgDQAKgCAOAAQANAAAKACQAKACAIADQAFADABACQABADgBAFIgRBgQgBAGgGABIgYAFQgMACgNAAQgMAAgJgEgAmOgrQgGACgFADQgFAEgDAFQgDAGgBAIIgGAfQgBAIABAFQABAGADADQADAEAFACQAGACAHAAQALAAAVgEIANhOQABgDgDgCQgLgEgNAAQgJAAgGACgAq5A9QgMgEgIgIQgHgIgDgMQgCgMACgOIAKg2QACgOAHgLQAGgLAKgIQAKgIANgEQANgEAQAAQANAAAKADQAKADAHAFQAHAFAEAIQAEAHABAKQACAHgHACIgJADQgGACgBgGQgBgHgDgFQgDgFgEgEQgFgDgGgCQgHgBgJAAQgLAAgIACQgJADgHAFQgGAFgEAIQgEAHgCAJIgKA2QgBAKABAHQACAIAFAFQAEAFAIACQAIADAKAAQAJAAAIgCQAHgBAGgEQAFgDAFgFQAEgFAEgHQADgGAGACIAKAEQAFACgDAGQgFAKgHAIQgHAHgJAFQgIAGgLACQgLADgOAAQgUgCgHgDgAI2A+QgGAAABgFIAUhwQABgGAGAAIAKAAQAFAAgBAGIgTBwQgBAFgGAAgAIEA+QgGAAABgFIANhJQACgHgBgFQgBgGgDgDQgDgEgGgCQgFgCgIAAQgKAAgIACQgHABgGADIgRBgQgBAFgGAAIgKAAQgGAAABgFIAdimQABgFAGAAIAKAAQAGAAgBAFIgJAyQAGgDAJgBQAIgBAMAAQAMAAAJADQAIADAFAHQAFAGABAJQACAJgCAMIgNBIQgBAFgGAAgAEJA+QgGAAABgFIANhJQABgHgBgFQgBgGgDgDQgDgEgFgCQgGgCgHAAQgOAAgPAFQgDABAAADIgRBdQgBAFgFAAIgLAAQgFAAABgFIARhkIAEgIQACgDAGgCQALgEAMgCQALgCANAAQAMAAAJADQAJADAEAHQAFAGACAJQABAJgBAMIgNBIQgCAFgFAAgAADA+QgFAAABgFIAThwQABgGAGAAIAKAAQAFAAgBAGIgTBwQgBAFgGAAgAivA+QgGAAABgFIANhKIABgMQgBgFgDgEQgCgDgFgCQgFgCgHAAQgNAAgQAHQACAIgCAMIgNBLQgBAFgGAAIgKAAQgGAAABgFIANhKQACgHgBgFQgBgFgDgEQgDgDgEgCQgFgCgHAAQgNAAgKAEQgEACAAADIgRBdQgBAFgFAAIgLAAQgFAAABgFIARhkIAEgIQACgDAGgCQAKgEALgCQAKgCALAAQAKAAAHACQAHADAFAEQAMgEALgDQALgCALAAQALAAAIADQAIADAFAGQAEAHABAJQACAJgCALIgNBJQgCAFgFAAgAnzA+QgGAAABgFIANhJQABgHgBgFQgBgGgDgDQgDgEgFgCQgGgCgHAAQgKAAgIACQgIABgGADIgRBgQgBAFgFAAIgLAAQgGAAACgFIAdimQABgFAGAAIAKAAQAGAAgCAFIgIAyQAGgDAIgBQAJgBALAAQAMAAAJADQAIADAFAHQAFAGACAJQABAJgCAMIgMBIQgCAFgFAAgAJUhRQgHAAgCgCQgCgDABgGIAAgCQACgHADgCQACgDAHAAIABAAQAHAAACADQACACgBAHIAAACQgBAGgDADQgDACgHAAgAAhhRQgHAAgCgCQgCgDABgGIAAgCQACgHADgCQACgDAHAAIABAAQAHAAACADQACACgBAHIAAACQgBAGgDADQgDACgHAAg");
	this.shape.setTransform(72.9,11.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ46, new cjs.Rectangle(0,0,145.9,23.1), null);


(lib.Символ45 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0044B2").s().p("AjIBtQgQgFgJgLQgJgLgEgPQgDgPADgSIANhGQADgSAIgPQAIgOANgKQAMgKARgFQARgGAVAAQAOAAAWAGQAPAGAKALQAJAKADAPQADAQgDASIgMBGQgDATgIAOQgIAOgNAKQgNAKgRAFQgRAFgUAAQgagCgKgEgAibhSQgLADgIAHQgJAGgFAKQgFAKgDAMIgMBFQgCANACAKQACAJAGAHQAGAGAKAEQAKADAOAAQANAAAMgDQALgEAIgGQAIgHAGgJQAFgKACgNIANhFQACgMgCgKQgCgKgGgGQgGgHgKgDQgKgEgOAAQgNAAgMAEgAFDBuQgIAAABgIIAkjLQACgIAIAAIBDAAQAPAAAWAGIAOAHQAHAFAFAFIAIAMQADAHACAIQACAWgCAMIgKA4QgEATgIAPQgIAPgNAKQgOAKgRAFQgZAFgOAAgAFeBSIAuAAQAOAAAMgDQAMgEAJgHQAIgGAGgKQAGgKACgNIAKg4QACgNgCgKQgCgKgGgHQgHgHgKgDQgLgEgOAAIguAAgACjBuQgIAAABgIIAkjLQABgIAIAAIAOAAQAJAAgCAIIghC3IBiAAQAIAAgBAIIgCAMQgCAIgIAAgABnBuQgIAAgDgBQgDgBgBgFIgSg5QgEgOgHgFQgHgFgRAAIgjAAIgNBQQgBAIgJAAIgNAAQgIAAABgIIAkjLQABgIAHAAIBXAAQAQAAAMAFQALAFAHAJQAIAJACAMQACANgDAPQgCANgEAJQgFAKgHAIQgHAGgJAFQgKAFgMADQAJAFAEAMIAWBDQADAIgIAAgAAFgFIA/AAQAJAAAHgDQAIgCAGgFQAFgFAEgHQAEgHACgJQABgJgBgHQgBgHgEgFQgEgFgHgCQgHgDgJAAIg+AAgAllBuQgJAAAAgGIgNiJQgBgPABgRIgBAAQgFAPgHARIg+CIQgDAHgJAAIgNAAQgIAAgBgGIgRjNQgBgIAIAAIAQAAQAJAAAAAHIAJCGIAAAlIABAAIANglIA8iDQADgHAJAAIAMAAQAJAAABAHIAMCDQACAPgBAWIABAAQAFgTAHgSIA4iGQADgHAJAAIAPAAQAHAAgDAIIhZDMQgCAHgJAAg");
	this.shape.setTransform(50.6,11.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ45, new cjs.Rectangle(0,0,101.2,23), null);


(lib.Символ44 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0044B2").s().p("AHIBvQgGgBgFgDQgGgDgEgFIgGgJQgDgGAHgDIAHgEQAGgCACAEQADAIAHADQAGAEAKABQAHgBAGgCQAGgCAEgDQAFgEADgFQADgGABgIIACgMQgTAFgOgBQgLAAgJgDQgIgDgFgGQgEgGgCgJQgBgIACgMIALg/QABgGAGAAIAJAAQAGAAgBAGIgMBAQgBAIABAFQAAAFADADQADADAGACQAFACAHgBQAKABAUgFIAQhXQABgGAGAAIAJAAQAGAAgBAGIgVB1QgDAMgEAKQgFAKgHAFQgIAHgJADQgKADgNAAQgIAAgHgCgAFRA5QgJgDgFgHQgFgHgCgJQgBgJACgLIAFgcQACgLAFgIQAFgJAIgHQAIgGAKgDQAKgCAMAAQAMAAAJACQAJADAGAGQAGAGACAHQACAIgCAJQgCAIgEAGQgEAGgHADQgHAEgJACQgKACgMAAQgOAAgTgDIgCAKQgBAGABAFQABAFAEAEQADAEAFABQAGACAHAAQAMAAAIgEQAJgDAGgIQAFgGAFAEIAFADQAFADgEAGQgFAGgFAEQgGAEgHADIgOAFQgIABgJAAQgMAAgKgEgAFugsQgGACgFAEQgFAEgDAFQgDAGgCAGIgBAIQARADAQAAIAMgBIAKgDIAHgHQACgDABgFQABgEgBgFQgBgDgDgEQgEgCgFgCQgGgBgIAAQgHAAgGACgABnA5QgJgDgGgGQgFgGgCgJQgCgJACgKIAGghQACgLAFgIQAEgJAIgGQAHgFAKgDQAKgDANABQAJAAAIABQAHACAFAEQAGAEADAGQADAFACAIQABAGgGACIgHACQgGADgBgGQgCgKgHgFQgHgEgLAAQgIAAgGABQgGACgEAEQgEADgDAFQgDAFgBAHIgGAiQgCAGABAFQABAFAEADQADAEAFACQAFACAIAAQAXAAALgUQACgHAGADIAIACQAFADgDAFQgEAJgGAFQgFAGgHAEQgHAEgIACQgIACgKAAQgMAAgJgEgAgTA6QgJgDgGgGQgGgGgCgIQgCgIACgKIAGglQACgLAFgHQAFgJAIgFQAHgGAJgDQAKgCAMAAQAMAAAKACQAJADAFAGQAGAHACAIQACAIgCALIgGAkQgCALgFAHQgEAIgIAGQgHAGgKACQgLADgMAAQgLAAgJgDgAAGgrQgGABgDAEQgFADgDAFQgDAEgBAHIgHAkQgBAGACAEQABAFADADQAEAEAFACQAGACAGAAQAHAAAGgCQAGgCAFgEQAFgDACgFQADgEACgGIAGgkQABgHgBgEQgBgFgEgDQgDgEgGgBQgFgCgHAAQgIAAgGACgAlgA5QgJgDgFgHQgFgHgCgJQgBgJACgLIAFgcQACgLAFgIQAFgJAIgHQAIgGAKgDQAKgCAMAAQAMAAAJACQAJADAGAGQAGAGACAHQACAIgCAJQgCAIgEAGQgEAGgHADQgHAEgJACQgKACgMAAQgOAAgTgDIgCAKQgBAGABAFQABAFAEAEQADAEAFABQAGACAHAAQAMAAAIgEQAJgDAGgIQAFgGAFAEIAFADQAFADgEAGQgFAGgFAEQgGAEgHADIgOAFQgIABgJAAQgMAAgKgEgAlDgsQgGACgFAEQgFAEgDAFQgDAGgCAGIgBAIQARADAQAAIAMgBIAKgDIAHgHQACgDABgFQABgEgBgFQgBgDgDgEQgEgCgFgCQgGgBgIAAQgHAAgGACgAnVA5QgJgDgFgGQgGgGgBgJQgCgJACgKIAGghQACgLAEgIQAFgJAHgGQAHgFAKgDQAKgDANABQAKAAAHABQAIACAFAEQAFAEAEAGQADAFABAIQABAGgGACIgHACQgGADgBgGQgCgKgGgFQgHgEgMAAQgHAAgGABQgGACgEAEQgFADgDAFQgDAFgBAHIgGAiQgBAGABAFQABAFADADQADAEAGACQAFACAHAAQAYAAAKgUQADgHAGADIAHACQAGADgEAFQgEAJgFAFQgGAGgHAEQgHAEgIACQgIACgKAAQgMAAgJgEgAEWA5IgGgBIgCgDIgLgjQgBgHgFgDQgEgCgIAAIgTAAIgIAuQgBAGgGgBIgJAAQgGABABgGIAcieQABgGAGAAIAJAAQAGAAgBAGIgRBfIASAAIArgtQADgEAIAAIAJAAQAIAAgGAGIgtAuQAFACAEAFQAEAEACAHIAOApQACAHgHgBgAhgA5QgGAAABgFIALhCIhPAAIgLBCQgBAFgGAAIgKAAQgGAAABgFIAaiXQABgGAGAAIALAAQAGAAgBAGIgMBAIBPAAIALhAQABgGAGAAIALAAQAGAAgBAGIgbCXQgBAFgGAAgAohA5QgGAAABgFIAbiXQABgGAGAAIAKAAQAGAAgBAGIgaCXQgCAFgGAAg");
	this.shape.setTransform(55.1,11.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ44, new cjs.Rectangle(0,0,110.2,22.6), null);


(lib.Символ43 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABgBHQgFAAgBgCQgCgCACgFIARhhIgeAAQgFAAgBgCQgBgBAAgGIAEgSQABgFABgBQADgCAFAAIBjAAQAEAAACACQABACAAAEIgEASQAAAFgDACQgCACgFAAIgdAAIgSBhQgBAFgCACQgCACgFAAgAgyBHQgFAAgCgCQgBgCABgFIAWh8QABgFACgBQADgCAEAAIBTAAQAEAAACACQACABgBAFIgDASQgBAFgCACQgDACgEAAIg0AAIgDASIApAAQAEAAADACQABABgBAFIgDARQgBAFgCACQgCACgFAAIgqAAIgDATIA2AAQAEAAACACQABABAAAFIgDASQgCAFgCACQgCACgFAAgAi2BHQgFAAgBgCQgCgCACgFIAVh8QABgEACgCQADgCAEAAIA7AAQAKAAAIADQAIACAEAGQAFAEADAIQABAIgBAIQgCAKgFAHQgEAFgJAGIAAABQASAHgFAcQgBAJgFAIQgEAGgIAFQgHAFgJACQgJADgMAAgAiRAnIAXAAQAHAAADgEQAEgDACgFQAAgGgCgDQgDgDgHAAIgWAAgAiHgQIAUAAQAFAAAEgDQADgDABgFQABgGgCgCQgDgDgGAAIgTAAg");
	this.shape.setTransform(19,7.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ43, new cjs.Rectangle(0,0,38,14.2), null);


(lib.Символ42 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D22D27").s().p("AF3DrQgLAAgDgEQgDgEACgKIA1kxQADgNAFgFQAFgHANgEQAWgJAagEQAagDAeAAQAcgBAUAIQAUAIAMAOQALAPAEAUQADAUgFAaIgJA1QgEAagLATQgKAUgRAOQgRANgWAGQgXAHgcAAIgegDIgOBVQgCAKgFAEQgFAEgKAAgAH0g0IgCADIgSBnIAVACQAPAAAJgHQAJgGACgOIALg8QACgLgGgHQgGgFgOgBQgOAAgJADgANNB/QgVgHgNgPQgNgPgEgUQgFgVAEgZIAKg2QAEgZAMgUQALgTASgNQARgNAYgHQAYgHAdABQAdgBAWAIQAVAIAOAOQANAPAEAUQAFAVgFAZIgJA2QgFAZgLATQgLAUgSANQgRAOgYAGQgYAHgeAAQgdAAgWgIgAN+gdIgKA7QgDANAGAGQAHAHAPAAQAPAAAJgHQAJgGADgNIAKg7QADgNgHgHQgGgGgQAAQgeAAgFAagAjgB/QgUgIgMgPQgLgOgEgWQgDgUAEgbIAKg0QAEgaALgUQALgTARgNQAQgNAYgGQAXgFAfAAQAfAAAXADQAYAEAQAJQALAGADAFQACAGgCAMIgiC8QgCALgEAEQgFAFgLADQgYAGgbADQgaADgdAAQgbAAgUgIgAifgwQgIAGgDAOIgKA7QgCANAGAFQAGAHANAAQAPAAALgCIAShnQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBAAAAAAQgHgCgMgBQgRAAgIAHgArsCAQgVgJgMgOQgMgPgEgUQgDgVAEgbIAKg1QAEgZALgUQALgTARgNQARgNAYgHQAXgFAeAAQAVAAARAEQARAFAMAJQAMAJAIANQAHANADAPQACALgEAFQgEAGgLAEIgsAPQgMAEgFgDQgFgDgCgMQgCgJgHgFQgHgFgLAAQgNAAgIAHQgIAGgDANIgKA/QgDANAGAGQAFAIANgBQAKAAAIgEQAIgFAGgKQAGgMAHgCQAGgDAKAEIAtAOQAKADACAHQACAHgGAKQgKARgNANQgNANgQAIQgPAJgTADQgTAFgWAAQgdAAgVgHgAxMB/QgVgJgNgPQgNgPgEgWQgEgVAFgZIAJgzQAFgYALgUQALgSASgNQASgOAYgHQAYgHAdABQAbAAAVAFQAWAGANALQAOANAGAQQAGASgDAVQgDARgIANQgJANgOAJQgOAIgTAFQgTAFgXAAIg3gDIgCAKQgDAQAHAIQAGAIAQAAQAaAAARgSQAHgHAFgCQAGgBAKAFIAgAQQAJAFABAIQABAGgHAKQgiAvhVAAQgeAAgXgIgAwMg9QgJAHgDAPIgCAGIAiACQAPAAAIgEQAIgFABgJQACgKgHgFQgHgFgPAAQgPAAgKAIgA4LCBQgWgGgNgMQgNgNgEgWQgDgUAFgfIAOhNIgVAAQgLAAgDgEQgEgFACgKIAHgkQACgLAEgEQAFgFAKAAIAWAAIAHgoQACgKAFgEQAFgEAKAAIA2AAQAKAAAEAEQADAEgCAKIgHAoIAjAAQAKAAADAFQADAEgBALIgHAkQgCAKgFAFQgFAEgKAAIgiAAIgNBHQgDAUAGAHQAGAIASAAQAMAAADAEQAEADgCAMIgIAqQgCALgFAEQgEAEgMAAIgFAAQgeAAgUgFgAWICDQgWAAgGgIQgIgIAEgWIAEgRQADgVAKgJQAKgIAWAAIAYAAQAWAAAHAIQAHAJgEAVIgDARQgEAWgJAIQgKAIgWAAgAS2CAQgKAAgDgFQgEgDACgLIAYiFQACgPgGgGQgGgGgPAAIgWABIgCACIgbCdQgCAKgFAEQgFAFgLAAIg1AAQgLAAgDgFQgEgEACgKIAjjDQADgNAEgFQAGgHANgEQAYgKAbgEQAbgFAdABQAbAAAUAGQATAIAMAOQALANAEAVQADATgFAaIgXCHQgCAKgFAEQgFAFgLAAgAKXCAQgLAAgDgFQgEgEACgKIAnjYQABgLAFgEQAFgFALAAIA1AAQALAAAEAFQADAEgCALIgmDYQgCAKgFAEQgFAFgLAAgAEJCAQgKAAgDgFQgDgDABgLIAYiGQACgNgFgGQgFgIgMABIgVACIgbCeQgCALgFADQgEAFgLAAIg2AAQgKAAgEgFQgDgEACgKIAYiGQACgOgFgHQgEgFgOAAIgRABIgCADIgcCcQgBAKgFAEQgGAFgKAAIg1AAQgKAAgEgFQgDgEACgKIAijDQACgNAFgFQAFgHANgEQAZgKAZgEQAagFAbABQASAAAPACQAOAEALAGQATgGATgEQAUgCATAAQAbAAATAGQASAIALAOQALANADAVQADATgFAaIgYCHQgBAKgFAEQgFAFgLAAgAmPCAQgLAAgDgFQgDgDACgLIAXiFQADgOgGgGQgGgIgPABQgQAAgIABIgcCfQgCAKgFAEQgFAFgKAAIg2AAQgKAAgEgFQgDgEACgKIA5lEQACgLAFgEQAFgEALAAIA1AAQALAAADAEQAEAEgCALIgPBUIAhgCQAcAAAUAGQATAIALAOQALANAEAUQADAUgEAaIgYCHQgCAKgFAEQgFAFgKAAgAz/CAQgLAAgDgFQgEgDACgLIAYiFQACgOgGgGQgGgIgPABQgQAAgHABIgcCfQgCAKgFAEQgFAFgLAAIg1AAQgLAAgDgFQgEgEACgKIA6lEQABgLAFgEQAFgEALAAIA2AAQAKAAAEAEQADAEgCALIgPBUIAigCQAbAAAUAGQATAIAMAOQALANAEAUQADAUgFAaIgYCHQgBAKgFAEQgFAFgLAAgAWRAVQgLAAgEgEQgDgEACgLQADgPAFgMQAEgNAIgJQAMgRAXgNIAggQIANgJQANgKADgTQADgMgIgIQgIgHgQAAQgVAAgMAHQgNAIgNAUQgHAMgGACQgFAEgKgFIgqgSQgKgEgCgGQgCgFAHgMQALgTAOgPQAOgPARgKQASgKAVgFQAWgEAbAAQAeAAAYAGQAXAIAQAOQAPAOAGATQAGAUgEAXQgCAOgGANQgFAMgJALQgOASgUALIgwAaQgVANgCANQgCALgFAEQgFAEgMAAgALWiUQgVABgGgJQgHgHAEgVIABgFQAEgVAJgIQAJgHAVgBIAYAAQAVABAHAHQAGAIgEAVIgBAFQgEAVgJAHQgJAJgUgBg");
	this.shape.setTransform(162.2,23.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ42, new cjs.Rectangle(0,0,324.4,47), null);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0948B0").s().p("AFlCjQgLgCgJgEQgJgFgGgGQgGgHgEgJQgDgGACgFQADgFAIgEIAcgNQAIgDAEABQADABADAFQAEAGAFADQAFADAGAAQAKAAAFgFQAGgFACgKIACgOIgXACQgSAAgOgFQgOgFgIgLQgIgKgCgOQgDgPAEgSIAEgbQAEgSAHgNQAHgOAMgIQAMgJARgEQAQgFAVAAQAVAAAQADQARADALAGQAIAEACAEQACADgCAJIgbCYQgEATgHAPQgHAOgMAJQgMAKgQAFQgQAEgUAAQgNAAgLgCgAGSgjQgGAFgCAJIgFAfQgCAIAEAFQAFAEAJAAIARgCIALg9QAAgBAAAAQABAAgBgBQAAAAAAAAQAAAAAAAAQgEgCgKAAQgLAAgGAFgAknCjQgLgCgJgEQgJgFgGgGQgGgHgEgJQgDgGACgFQADgFAIgEIAcgNQAIgDAEABQADABADAFQAEAGAFADQAFADAGAAQAKAAAFgFQAGgFACgKIACgOIgXACQgSAAgOgFQgOgFgIgLQgIgKgCgOQgDgPAEgSIAEgbQAEgSAHgNQAHgOAMgIQAMgJARgEQAQgFAVAAQAVAAAQADQARADALAGQAIAEACAEQACADgCAJIgbCYQgEATgHAPQgHAOgMAJQgMAKgQAFQgQAEgUAAQgNAAgLgCgAj6gjQgGAFgCAJIgFAfQgCAIAEAFQAFAEAJAAIARgCIALg9QAAgBAAAAQABAAgBgBQAAAAAAAAQAAAAAAAAQgEgCgKAAQgLAAgGAFgASaBWQgPgGgJgLQgJgKgDgPQgCgPADgSIAGgiQADgRAIgOQAIgNANgJQAMgJAQgFQARgFAUAAQATAAAPAEQAOAFAKAIQAKAIAEALQAEAMgCAPQgCAMgGAJQgGAJgKAGQgJAGgNADQgOAEgQAAIgmgCIgCAHQgCALAFAFQAFAFALAAQARAAAMgMQAFgFAEgBQAEgBAHAEIAWALQAGADABAFQABAFgFAHQgYAgg6AAQgWAAgPgFgATGgsQgGAFgDAKIgBAEIAYACQAKAAAFgDQAGgDABgHQABgHgFgDQgEgEgLAAQgKAAgHAGgAPbBZQgRgDgMgGQgIgEgBgEQgCgDACgJIAljTQABgHADgDQAEgDAHAAIAlAAQAIAAACADQADADgCAHIgKA6IAXgCQATAAAOAGQANAFAIAKQAIAKACAOQADAPgEARIgGAkQgDATgIAOQgHAOgMAIQgMAKgQAEQgRAEgVAAQgUAAgQgCgAQFgmIgMBHIAAACQAFABAJAAQALAAAGgEQAGgFACgJIAHgqQABgIgEgEQgEgEgJAAQgLAAgHACgALoBWQgPgFgJgKQgJgKgDgPQgDgOADgRIAGglQADgSAIgOQAIgNAMgJQANgJAQgFQARgFAUAAQAUAAAPAGQAPAFAJAKQAJAKADAOQADAPgDARIgGAlQgDASgIANQgIAOgMAJQgMAJgRAFQgRAEgUAAQgUAAgPgFgAMJgWIgHApQgCAIAFAFQAEAFALAAQAKAAAHgFQAGgFACgIIAHgpQACgJgFgFQgEgEgLAAQgVAAgEASgAhpBWQgPgFgJgKQgJgKgDgPQgDgOADgRIAGglQADgSAIgOQAIgNAMgJQANgJAQgFQARgFAUAAQAUAAAPAGQAOAFAJAKQAJAKADAOQADAPgDARIgGAlQgDASgIANQgIAOgLAJQgMAJgRAFQgRAEgUAAQgUAAgPgFgAhIgWIgHApQgCAIAFAFQAEAFALAAQAKAAAHgFQAGgFACgIIAHgpQACgJgFgFQgEgEgLAAQgVAAgEASgAoRBZQgNgDgKgFQgJgFgGgIQgFgHgCgKQgCgGADgFQADgEAHgDIAdgJQAIgCADABQADAAADAGQACAFAGADQAGADAJAAQAMAAAHgDQAHgDABgFQABgGgGgDQgGgCgUgBQgQgBgNgEQgMgEgIgHQgIgGgCgLQgDgKACgOQADgOAGgKQAHgKAKgHQALgHAPgDQAOgEATAAQAPAAAMADQAMACAJAFQAIAEAGAHQAFAHAEAJQACAGgCAFQgDAEgHADIgaALQgIAEgDgCIgGgGQgHgKgRAAQgMAAgFACQgFACAAAGQgBAFAFACQAFADARABQATACAOADQANAFAIAGQAIAGACALQADAKgDANQgCAOgHALQgHAKgLAIQgMAHgPAEQgQADgTAAQgRAAgMgCgAsYBWQgPgFgJgKQgJgKgDgPQgDgOADgRIAGglQADgSAIgOQAIgNAMgJQANgJAQgFQARgFAUAAQAUAAAPAGQAPAFAJAKQAJAKADAOQADAPgDARIgGAlQgDASgIANQgIAOgMAJQgMAJgRAFQgRAEgUAAQgUAAgPgFgAr3gWIgHApQgCAIAFAFQAEAFALAAQAKAAAHgFQAGgFACgIIAHgpQACgJgFgFQgEgEgLAAQgVAAgEASgAJvBXQgQgEgJgJQgJgJgDgOQgCgPAEgUIAJg2IgOAAQgIAAgCgDQgCgDABgHIAFgaQABgHADgDQADgDAHAAIAPAAIAFgbQACgIADgCQADgDAHAAIAmAAQAHAAACADQADACgBAIIgFAbIAYAAQAHAAACADQACADgBAHIgEAaQgCAHgDADQgEADgHAAIgXAAIgJAxQgDAOAFAFQAEAFANAAQAHAAADADQACADgBAHIgGAdQgBAIgDADQgDADgIAAIgFAAQgUAAgNgEgADrBWQgHAAgCgDQgDgCACgIIAQhcQACgKgEgEQgFgFgKAAIgPACIgCABIgTBsQgBAHgDADQgEADgHAAIglAAQgIAAgCgDQgDgDACgHIAYiHQACgIADgEQAEgFAJgDQARgGASgEQATgDAUAAQATAAAOAFQANAFAIAKQAIAJACAOQADAOgDASIgRBdQgBAHgEADQgDADgHAAgAAtBWQgHAAgCgDQgDgDABgHIAbiWQABgHAEgDQADgDAIAAIAlAAQAHAAACADQADADgBAHIgbCWQgBAHgEADQgDADgIAAgAuWBWQgHAAgCgDQgCgCABgIIAQhcQACgJgEgFQgFgFgKAAQgLAAgFACIgTBtQgCAHgDADQgEADgHAAIglAAQgIAAgCgDQgCgDABgHIAojgQABgIADgCQAEgDAHAAIAlAAQAIAAACADQADACgCAIIgKA6IAXgCQATAAAOAFQANAFAIAKQAIAJADAOQACAOgDASIgRBdQgBAHgEADQgDADgHAAgAyJBWQgHAAgEgCQgEgDAAgGIgEhOQgBgVAFgoIgDAAQgLApgHAUIggBNQgDAHgFADQgEACgIAAIgpAAQgHAAgEgDQgEgCAAgGIgOjXQgBgIADgDQACgDAHAAIAqAAQAJAAAEACQAEADAAAHIAABZQgBAegFAeIACAAQAEgWANgmIAlhZQADgHAEgDQAFgCAJAAIAkAAQAJAAAEADQAEACAAAHIAFBZQAAAkgEAYIADAAQAEgYALgkIAehZQADgHAFgCQAEgDAKAAIAmAAQAHAAACADQABAEgDAHIhaDWQgDAHgEADQgEACgIAAgApohAQgHAAgCgCQgCgCABgHIAMhEQABgHADgCQACgCAIAAIAeAAQAHAAACACQADADgCAGIgUBEQgCAHgDACQgCACgIAAgABZhoQgOAAgFgGQgEgFACgOIABgEQADgOAGgGQAGgFAPAAIARAAQAOAAAFAFQAEAGgDAOIAAAEQgDAOgGAFQgGAGgPAAg");
	this.shape.setTransform(132,16.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ41, new cjs.Rectangle(0,0,264.1,33.1), null);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.maska_07();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ38, new cjs.Rectangle(0,0,143,156), null);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.maska_06();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ37, new cjs.Rectangle(0,0,151,157), null);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.maska_05();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ36, new cjs.Rectangle(0,0,146,157), null);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.maska_03();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ33, new cjs.Rectangle(0,0,151,145), null);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.maska_02();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ32, new cjs.Rectangle(0,0,145,145), null);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.maska_01();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ31, new cjs.Rectangle(0,0,144,145), null);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0948B0").s().p("ArAD1QhkAAAAhkIAAkhQAAhkBkAAIWBAAQBkAAAABkIAAEhQAABkhkAAg");
	this.shape.setTransform(80.5,24.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ27, new cjs.Rectangle(0,0,161,49), null);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0948B0").s().p("Ag4CRQgSABgFgHQgGgGADgRIADgPQACgQAJgHQAHgHASAAIATAAQASAAAFAHQAEAGgCARIgBAPQgEARgHAGQgIAHgSgBgAgxA6QgJAAgDgEQgDgCACgJQACgNAEgKQAEgKAGgIQAKgMASgJIAYgOIAKgHQALgIACgPQACgKgGgGQgGgGgNAAQgPAAgKAGQgKAGgLARQgFAJgFACQgEACgIgDIghgOQgIgEgCgEQgBgEAFgKQAJgQALgLQALgMAOgIQAOgIARgEQARgDAVgBQAYABASAFQATAGAMALQANAMAFAPQAEAPgDASQgBAMgFALQgEAJgHAJQgMAOgQAHIgmAVQgRAKgBAMQgCAJgDACQgEAEgJAAg");
	this.shape.setTransform(10.6,14.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ22, new cjs.Rectangle(0,0,21.3,29.1), null);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.rus_big();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ21, new cjs.Rectangle(0,0,230,227), null);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.canada_big();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ20, new cjs.Rectangle(0,0,243,241), null);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AgEAyQgBgGAFgDIAMgEQAFgCACAHQACAHADAFQAEAFAFAEQAFADAGACQAHACAIAAQALAAAJgCQAJgCAGgEQAHgEAEgFQADgGACgIQABgJgEgGQgDgFgJgDQgKgEgPgBIgSgDQgIgCgIgEQgJgDgFgFQgGgGgCgJQgDgKACgMQADgLAGgKQAFgJAKgGQAJgGANgDQANgEAQAAQAMAAAJADQAKACAHAFQAGAFAFAIQAFAHADAJQACAGgHACIgKAFQgGACgCgFQgCgHgDgEQgDgFgFgDQgEgDgHgCQgGgBgIAAQgKAAgJACQgIABgFAEQgGADgEAFQgDAFgBAHQgCAIADAGQADAFAHADQAJAFAWADQANABAJADQAKADAJAFQAIAGAEAKIACAMIgBANQgCANgGAJQgGAKgKAGQgJAGgOADQgNAEgRAAQg1AAgIgrgAhoBZQgGAAgBgFIghilQgCgHAHAAIAKAAQAKAAAAAGIAWB3IADAXIABAAIAKgXIBAh3IAFgFIAIgBIAJAAQAHAAgEAHIhbCkQgCAGgHAAg");
	this.shape.setTransform(14.6,9.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ19, new cjs.Rectangle(0,0,29.2,18.6), null);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D22D27").s().p("ArqCMQgLgEgJgFQgIgGgHgJQgHgIgFgJQgEgJgDgKQgCgLAAgMIAPhiQADgRANgdIANgSIARgOQAMgJAegMQAQgEAmgDQAVAAARAEQARAFANAJQAMAIAIAOQAIANADATQACAIgDAFQgDAFgKADIgpAOQgJACgEgBQgEgDgDgJQgCgNgJgHQgIgGgRAAQgMAAgIADQgJACgGAFQgHAFgDAIQgEAIgCAKIgNBIQgCALABAIQABAHAFAGQAEAFAIACQAIADALAAQAQAAAMgHQALgGAHgNQAGgJAFgDQAFgCAIADIAqAQQAHADACAFQACAFgFAJQgJARgNANQgNANgQAJQgQAIgTAFQgUAEgXAAQgkgCgOgGgALqCOQgOAAgGgEQgGgDAAgKIgFgcIhWAAIgOAcQgFAKgHADQgGAEgOAAIgsAAQgJAAgCgEQgBgEAEgJICJj8QAEgIAFgDQAFgDAJAAIAtAAQAJAAAEADQAEADACAIIAwD8QABAJgDAEQgEAEgJAAgALEAiIgGguQgCgaACgWIABgIIgEAAQgJAlgJATIgWAuIAxAAgAEeCOQgKAAgDgEQgDgDACgKIAsj5QACgKAEgDQAEgEAKAAIBhAAQA6AAAbAhQAHAHAEAKQAFAJACALQACAKAAANIgNBUQgJAhgHANIgNASIgQAPQgaAPgQAFQgiAHgUAAgAFoBIIAhAAQAuAAAIgsIAKg3QACgMgCgHQgBgJgFgFQgFgFgIgEQgIgCgMAAIggAAgADJCOQgPAAgGgEQgFgDgBgKIgEgcIhXAAIgOAcQgFAKgGADQgHAEgOAAIgrAAQgIAAgCgEQgCgEAFgJICHj8QAFgIAFgDQAEgDAJAAIAuAAQAJAAAEADQAEADACAIIAvD8QACAJgEAEQgEAEgJAAgACjAiIgHguQgCgaACgWIACgIIgEAAQgKAlgIATIgXAuIAyAAgAhrCOQgLAAgEgIIgshfQgIgRgFgUQgFgSgDgaIgDAAQADA5gIAtIgMBBQgCAKgEADQgEAEgKAAIgqAAQgJAAgEgEQgDgDACgKIAsj5QACgKAFgDQAEgEAJAAIAuAAQALAAAEAIIAwBnQANAlAIAjIADAAQgFglAAgNQAAgPAFgkIALhBQACgKAEgDQAEgEAKAAIAqAAQAJAAAEAEQACADgCAKIgrD5QgCAKgEADQgFAEgJAAgAliCOQgOAAgGgEQgGgDAAgKIgFgcIhWAAIgOAcQgFAKgHADQgGAEgOAAIgsAAQgJAAgCgEQgBgEAEgJICJj8QAEgIAFgDQAFgDAJAAIAtAAQAJAAAEADQAEADACAIIAwD8QABAJgDAEQgEAEgJAAgAmIAiIgGguQgCgaACgWIABgIIgEAAQgJAlgJATIgWAuIAxAAg");
	this.shape.setTransform(89.2,16.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ18, new cjs.Rectangle(8.9,1.5,160.7,29.6), null);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.pole();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ15, new cjs.Rectangle(0,0,400,184), null);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.iihf_logo();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ10, new cjs.Rectangle(0,0,76,109), null);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(12.5,12);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0044B2").s().p("AtjFAIAAp/IbGAAQAJALg4D7QgbB8geB7QgMBFgbAdQgeAgg+AAg");
	this.shape.setTransform(86.8,32);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ3, new cjs.Rectangle(0,0,173.7,64), null);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bg();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ1, new cjs.Rectangle(0,0,600,300), null);


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ38();
	this.instance.parent = this;
	this.instance.setTransform(-531.3,-468.1,1,1,0,0,0,71.5,78);

	this.instance_1 = new lib.Символ38();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-531.3,53,1,1,0,0,0,71.5,78);

	this.instance_2 = new lib.Символ37();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-531.3,-294.4,1,1,0,0,0,75.5,78.5);

	this.instance_3 = new lib.Символ36();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-531.3,-120.7,1,1,0,0,0,73,78.5);

	this.instance_4 = new lib.Символ38();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-531.3,574.1,1,1,0,0,0,71.5,78);

	this.instance_5 = new lib.Символ37();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-531.3,226.7,1,1,0,0,0,75.5,78.5);

	this.instance_6 = new lib.Символ36();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-531.3,400.4,1,1,0,0,0,73,78.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ39, new cjs.Rectangle(-606.8,-546.1,151,1198.3), null);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// maska_07.png - копия
	this.instance = new lib.Символ39();
	this.instance.parent = this;
	this.instance.setTransform(495.5,574,1,1,0,0,0,75.5,271);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-297},49).to({_off:true},1).wait(50));

	// maska_07.png
	this.instance_1 = new lib.Символ39();
	this.instance_1.parent = this;
	this.instance_1.setTransform(495.5,1616,1,1,0,0,0,75.5,271);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:745},49).to({y:53},50).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-186.8,-243.2,151,2240.3);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ43();
	this.instance.parent = this;
	this.instance.setTransform(57.3,3.7,1,1,0,0,0,19,7.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ29, new cjs.Rectangle(38.3,-3.4,38,14.2), null);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ29();
	this.instance.parent = this;
	this.instance.setTransform(82.4,25.7,1.1,1.1,0,0,0,56.8,5.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ27();
	this.instance_1.parent = this;
	this.instance_1.setTransform(80.5,24.5,1,1,0,0,0,80.5,24.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ26, new cjs.Rectangle(0,0,161,49), null);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ26();
	this.instance.parent = this;
	this.instance.setTransform(77.5,24.5,1,1,0,0,0,80.5,24.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:1.05,scaleY:1.05,x:77.4,y:27.5},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3,0,161,49);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ42();
	this.instance.parent = this;
	this.instance.setTransform(135.6,9.7,1,1,0,0,0,162.2,23.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ24, new cjs.Rectangle(-26.6,-13.8,324.3,47), null);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ41();
	this.instance.parent = this;
	this.instance.setTransform(104.4,11.5,1,1,0,0,0,132.1,16.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ23, new cjs.Rectangle(-27.7,-5,264.1,33.1), null);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ51();
	this.instance.parent = this;
	this.instance.setTransform(84.4,15.3,1,1,0,0,0,71.8,14.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ17, new cjs.Rectangle(12.6,0.5,143.6,29.6), null);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ49();
	this.instance.parent = this;
	this.instance.setTransform(74.2,4.1,1,1,0,0,0,67.7,9.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ16, new cjs.Rectangle(6.5,-5.7,135.4,19.6), null);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ48();
	this.instance.parent = this;
	this.instance.setTransform(112,7.5,1,1,0,0,0,111.2,14.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ12, new cjs.Rectangle(0.8,-6.6,222.6,28.2), null);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ47();
	this.instance.parent = this;
	this.instance.setTransform(91.6,13.6,1.14,1.14,0,0,0,82.2,18.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ11, new cjs.Rectangle(-2.1,-7.9,187.4,43.1), null);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ44();
	this.instance.parent = this;
	this.instance.setTransform(69.8,11.2,1,1,0,0,0,55.1,11.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ8, new cjs.Rectangle(14.7,-0.1,110.2,22.6), null);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ45();
	this.instance.parent = this;
	this.instance.setTransform(42.9,13.4,1,1,0,0,0,50.6,11.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ7, new cjs.Rectangle(-7.7,1.9,101.2,23), null);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ46();
	this.instance.parent = this;
	this.instance.setTransform(41.3,5.9,1,1,0,0,0,72.9,11.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ6, new cjs.Rectangle(-31.6,-5.6,145.9,23), null);


(lib.Анимация3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ31();
	this.instance.parent = this;
	this.instance.setTransform(0,-641.2,1,1,0,0,0,72,72.5);

	this.instance_1 = new lib.Символ33();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,53,1,1,0,0,0,75.5,72.5);

	this.instance_2 = new lib.Символ32();
	this.instance_2.parent = this;
	this.instance_2.setTransform(0,226.6,1,1,0,0,0,72.5,72.5);

	this.instance_3 = new lib.Символ31();
	this.instance_3.parent = this;
	this.instance_3.setTransform(0,400.2,1,1,0,0,0,72,72.5);

	this.instance_4 = new lib.Символ33();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,-467.6,1,1,0,0,0,75.5,72.5);

	this.instance_5 = new lib.Символ32();
	this.instance_5.parent = this;
	this.instance_5.setTransform(0,-294.1,1,1,0,0,0,72.5,72.5);

	this.instance_6 = new lib.Символ31();
	this.instance_6.parent = this;
	this.instance_6.setTransform(0,-120.5,1,1,0,0,0,72,72.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.5,-713.7,151,1186.4);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ35();
	this.instance.parent = this;
	this.instance.setTransform(232.2,910.8,0.8,0.8,-17,0,0,75.5,78.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ40, new cjs.Rectangle(-40.6,691.6,633.3,1747.3), null);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance = new lib.Анимация3("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(74.8,-256.3);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(49).to({_off:false},0).to({y:576.7},50).wait(1));

	// Слой 1
	this.instance_1 = new lib.Анимация3("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(74.8,56.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:784.7},49).to({y:1618.7},50).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.7,-657,151,1186.4);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// left
	this.instance = new lib.Символ34();
	this.instance.parent = this;
	this.instance.setTransform(14.5,11.8,0.8,0.8,-17,0,0,75.5,233.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ30, new cjs.Rectangle(-249.3,-685.9,387.7,941.3), null);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ12();
	this.instance.parent = this;
	this.instance.setTransform(128.7,64.5,1,1,0,0,0,129.7,10.3);

	this.instance_1 = new lib.Символ11();
	this.instance_1.parent = this;
	this.instance_1.setTransform(129.8,23.4,1,1,0,0,0,126.5,20.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ13, new cjs.Rectangle(-0.2,-4.9,222.6,80.7), null);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ8();
	this.instance.parent = this;
	this.instance.setTransform(58.3,8.1,0.93,0.93,0,0,0,62.5,8.7);

	this.instance_1 = new lib.Символ7();
	this.instance_1.parent = this;
	this.instance_1.setTransform(68.8,38.8,0.99,0.99,0,0,0,46.1,15.6);

	this.instance_2 = new lib.Символ6();
	this.instance_2.parent = this;
	this.instance_2.setTransform(55.4,64.2,1,1,0,0,0,55.4,6.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ9, new cjs.Rectangle(-31.6,0,147.9,75.1), null);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_249 = function() {
		this.gotoAndPlay(1);
	}
	this.frame_264 = function() {
		this.stop(0);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(249).call(this.frame_249).wait(15).call(this.frame_264).wait(11));

	// rigt
	this.instance = new lib.Символ40();
	this.instance.parent = this;
	this.instance.setTransform(998.1,-407.6,1,1,0,0,0,341.2,599.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(170).to({_off:false},0).to({x:698.1},9,cjs.Ease.get(1)).to({x:718.1},5,cjs.Ease.get(1)).wait(56).to({x:698.1},4,cjs.Ease.get(1)).to({x:958.1},5,cjs.Ease.get(1)).wait(1).to({x:998.1},0).to({x:698.1},9,cjs.Ease.get(1)).to({x:718.1},5,cjs.Ease.get(1)).wait(1).to({x:698.1},5,cjs.Ease.get(1)).to({x:958.1},4,cjs.Ease.get(1)).wait(1));

	// left
	this.instance_1 = new lib.Символ30();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-184.7,45,1,1,0,0,0,72,72.5);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(170).to({_off:false},0).to({x:55.3},9,cjs.Ease.get(1)).to({x:35.3},5,cjs.Ease.get(1)).wait(56).to({x:55.3},4,cjs.Ease.get(1)).to({x:-184.7},5,cjs.Ease.get(1)).wait(1).to({x:55.3},9,cjs.Ease.get(1)).to({x:35.3},5,cjs.Ease.get(1)).wait(1).to({x:55.3},5,cjs.Ease.get(1)).to({x:-184.7},4,cjs.Ease.get(1)).wait(1));

	// btn
	this.instance_2 = new lib.Символ25();
	this.instance_2.parent = this;
	this.instance_2.setTransform(243.2,126.1,1,1,0,0,0,80.5,24.5);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;
	new cjs.ButtonHelper(this.instance_2, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(170).to({_off:false},0).to({y:66.1,alpha:1},9,cjs.Ease.get(1)).to({y:76.1},5,cjs.Ease.get(1)).wait(55).to({x:283.2},5,cjs.Ease.get(1)).to({x:183.2,alpha:0},5,cjs.Ease.get(1)).wait(1).to({x:243.2,y:126.1},0).to({y:66.1,alpha:1},9,cjs.Ease.get(1)).to({y:76.1},5,cjs.Ease.get(1)).wait(1).to({x:283.2},5,cjs.Ease.get(1)).to({x:183.2,alpha:0},4,cjs.Ease.get(1)).wait(1));

	// text3-2
	this.instance_3 = new lib.Символ24();
	this.instance_3.parent = this;
	this.instance_3.setTransform(241.3,71.9,1,1,0,0,0,134,14.7);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(170).to({_off:false},0).to({y:17.9,alpha:1},9,cjs.Ease.get(1)).to({y:21.9},5,cjs.Ease.get(1)).wait(55).to({x:281.3},5,cjs.Ease.get(1)).to({x:181.3,alpha:0},5,cjs.Ease.get(1)).wait(1).to({x:241.3,y:71.9},0).to({y:17.9,alpha:1},9,cjs.Ease.get(1)).to({y:21.9},5,cjs.Ease.get(1)).wait(1).to({x:281.3},5,cjs.Ease.get(1)).to({x:181.3,alpha:0},4,cjs.Ease.get(1)).wait(1));

	// text3-1
	this.instance_4 = new lib.Символ23();
	this.instance_4.parent = this;
	this.instance_4.setTransform(241.1,-57.2,1,1,0,0,0,105.6,17.1);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(170).to({_off:false},0).to({y:-16.2,alpha:1},9,cjs.Ease.get(1)).to({y:-17.2},5,cjs.Ease.get(1)).wait(55).to({x:181.1},5,cjs.Ease.get(1)).to({x:301.1,alpha:0},5,cjs.Ease.get(1)).wait(1).to({x:241.1,y:-57.2},0).to({y:-16.2,alpha:1},9,cjs.Ease.get(1)).to({y:-17.2},5,cjs.Ease.get(1)).wait(1).to({x:181.1},5,cjs.Ease.get(1)).to({x:301.1,alpha:0},4,cjs.Ease.get(1)).wait(1));

	// rus_big
	this.instance_5 = new lib.Символ21();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-199.4,171.3,1,1,0,0,0,115,113.5);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(95).to({_off:false},0).to({x:11.5,y:85.3},9,cjs.Ease.get(1)).to({x:0.5,y:97.3},5,cjs.Ease.get(1)).wait(50).to({x:10.5,y:87.3},5,cjs.Ease.get(1)).to({x:-99.5,y:167.3,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(105));

	// canada_big
	this.instance_6 = new lib.Символ20();
	this.instance_6.parent = this;
	this.instance_6.setTransform(701.5,-116.1,1,1,0,0,0,121.5,120.5);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(95).to({_off:false},0).to({x:468.5,y:-3.1},9,cjs.Ease.get(1)).to({x:478.5,y:-13.1},5,cjs.Ease.get(1)).wait(50).to({x:468.5,y:-3.1},5,cjs.Ease.get(1)).to({x:548.5,y:-53.1,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(105));

	// ?
	this.instance_7 = new lib.Символ22();
	this.instance_7.parent = this;
	this.instance_7.setTransform(241,156.9,1,1,0,0,0,10.6,14.6);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(92).to({_off:false},0).to({y:94.9,alpha:1},9,cjs.Ease.get(1)).to({y:96.9},5,cjs.Ease.get(1)).wait(53).to({x:231},5,cjs.Ease.get(1)).to({x:291,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(105));

	// canada
	this.instance_8 = new lib.Символ18();
	this.instance_8.parent = this;
	this.instance_8.setTransform(241.1,122.3,1,1,0,0,0,89.2,18.1);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(92).to({_off:false},0).to({y:60.3,alpha:1},9,cjs.Ease.get(1)).to({y:61.3},5,cjs.Ease.get(1)).wait(53).to({y:62.3},0).to({x:231.1},5,cjs.Ease.get(1)).to({x:291.1,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(105));

	// vs
	this.instance_9 = new lib.Символ19();
	this.instance_9.parent = this;
	this.instance_9.setTransform(242.6,88.7,0.82,0.82,0,0,0,14.6,9.2);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(92).to({_off:false},0).to({y:28.7,alpha:1},9,cjs.Ease.get(1)).wait(63).to({alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(105));

	// rus
	this.instance_10 = new lib.Символ17();
	this.instance_10.parent = this;
	this.instance_10.setTransform(241.1,-70,1,1,0,0,0,85.2,15.6);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(92).to({_off:false},0).to({y:2,alpha:1},9,cjs.Ease.get(1)).to({y:0},5,cjs.Ease.get(1)).wait(53).to({x:261.1},5,cjs.Ease.get(1)).to({x:181.1,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(105));

	// text2-1
	this.instance_11 = new lib.Символ16();
	this.instance_11.parent = this;
	this.instance_11.setTransform(243.2,-103.5,1,1,0,0,0,75.1,9.3);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(92).to({_off:false},0).to({y:-31.5,alpha:1},9,cjs.Ease.get(1)).to({y:-33.5},5,cjs.Ease.get(1)).wait(53).to({x:263.2},5,cjs.Ease.get(1)).to({x:183.2,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(105));

	// text1-2
	this.instance_12 = new lib.Символ13();
	this.instance_12.parent = this;
	this.instance_12.setTransform(352.9,55.9,1,1,0,0,0,129.7,36);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(19).to({_off:false},0).to({y:25.9,alpha:1},10,cjs.Ease.get(1)).to({y:35.9},5,cjs.Ease.get(1)).wait(40).to({x:342.9},5,cjs.Ease.get(1)).to({x:602.9,alpha:0},5,cjs.Ease.get(1)).wait(5).to({_off:true},1).wait(185));

	// logo
	this.instance_13 = new lib.Символ10();
	this.instance_13.parent = this;
	this.instance_13.setTransform(168.5,65.5,1,1,0,0,0,38,54.5);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(14).to({_off:false},0).to({y:25.5,alpha:1},10,cjs.Ease.get(1)).to({y:35.5},5,cjs.Ease.get(1)).wait(47).to({x:158.5},5,cjs.Ease.get(1)).to({x:418.5,alpha:0},5,cjs.Ease.get(1)).wait(3).to({_off:true},1).wait(185));

	// text1-1
	this.instance_14 = new lib.Символ9();
	this.instance_14.parent = this;
	this.instance_14.setTransform(64.1,66,1,1,0,0,0,58.1,35.4);
	this.instance_14.alpha = 0;
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(9).to({_off:false},0).to({y:26,alpha:1},10,cjs.Ease.get(1)).to({y:36},5,cjs.Ease.get(1)).wait(55).to({x:54.1},5,cjs.Ease.get(1)).to({x:314.1,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(185));

	// bg3
	this.instance_15 = new lib.Символ15();
	this.instance_15.parent = this;
	this.instance_15.setTransform(776.8,123.1,1,1,-12,0,0,200,92);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({x:457.8,y:190.1},9,cjs.Ease.get(1)).to({x:467.8,y:200.1},5,cjs.Ease.get(1)).wait(59).to({x:443.8,y:203},5,cjs.Ease.get(1)).to({x:771.8,y:132.2},5,cjs.Ease.get(1)).wait(7).to({regX:199.9,rotation:-17,x:7.7,y:328.8},0).to({x:278.7,y:219.8},9,cjs.Ease.get(1)).to({x:267.7,y:226.8},5,cjs.Ease.get(1)).wait(55).to({x:277.7,y:216.8},5,cjs.Ease.get(1)).to({x:-16.4,y:330.8,alpha:0},5,cjs.Ease.get(1)).wait(1).to({x:57.7,y:326.8,alpha:1},0).to({x:277.7,y:216.8},9,cjs.Ease.get(1)).to({x:267.7,y:226.8},5,cjs.Ease.get(1)).wait(55).to({x:287.7,y:206.8},6,cjs.Ease.get(1)).to({x:27.7,y:346.8},4,cjs.Ease.get(1)).wait(1).to({x:57.7,y:326.8},0).to({x:277.7,y:216.8},9,cjs.Ease.get(1)).to({x:267.7,y:226.8},5,cjs.Ease.get(1)).wait(1).to({x:287.7,y:206.8},6,cjs.Ease.get(1)).to({x:27.7,y:346.8},3,cjs.Ease.get(1)).wait(1));

	// bg2
	this.instance_16 = new lib.Символ15();
	this.instance_16.parent = this;
	this.instance_16.setTransform(621.7,-280.9,1,1,-18,0,0,200,92);

	this.timeline.addTween(cjs.Tween.get(this.instance_16).to({x:384.7,y:-169.9},9,cjs.Ease.get(1)).to({x:394.7,y:-179.9},5,cjs.Ease.get(1)).wait(57).to({x:377.7,y:-172.9},5,cjs.Ease.get(1)).to({x:672.7,y:-266.9},5,cjs.Ease.get(1)).wait(9).to({scaleX:0.88,scaleY:0.88,x:535.7,y:-250.9},0).to({x:308.7,y:-185.9},9,cjs.Ease.get(1)).to({x:323.7,y:-187.9},5,cjs.Ease.get(1)).wait(55).to({x:313.7,y:-177.9},5,cjs.Ease.get(1)).to({x:548.7,y:-255.9,alpha:0},5,cjs.Ease.get(1)).wait(1).to({x:453.7,y:-267.9,alpha:1},0).to({x:313.7,y:-177.9},9,cjs.Ease.get(1)).to({x:323.7,y:-187.9},5,cjs.Ease.get(1)).wait(55).to({x:303.7,y:-167.9},6,cjs.Ease.get(1)).to({x:543.7,y:-267.9},4,cjs.Ease.get(1)).wait(1).to({x:453.7},0).to({x:313.7,y:-177.9},9,cjs.Ease.get(1)).to({x:323.7,y:-187.9},5,cjs.Ease.get(1)).wait(1).to({x:303.7,y:-167.9},6,cjs.Ease.get(1)).to({x:543.7,y:-267.9},3,cjs.Ease.get(1)).wait(1));

	// bg1
	this.instance_17 = new lib.Символ15();
	this.instance_17.parent = this;
	this.instance_17.setTransform(-289.2,135.1,1,1,16,0,0,200,92);

	this.timeline.addTween(cjs.Tween.get(this.instance_17).to({x:-77.3,y:182.1},9,cjs.Ease.get(1)).to({x:-87.3,y:172.1},5,cjs.Ease.get(1)).wait(55).to({x:-67.3,y:182.1},5,cjs.Ease.get(1)).to({x:-296.3,y:113},5,cjs.Ease.get(1)).wait(10).to({_off:true},1).wait(185));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-506.8,-430.2,1498.3,708.8);


// stage content:
(lib.hockey = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var bodyStyle = document.body.style;
		bodyStyle.margin = 0;
		bodyStyle.padding = 0;
		
		var _this = this;
		
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
		
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		
		  function fl_MouseOverHandler_5()
		{
		    _this.an.gotoAndPlay(250);
		
		    
		}
		
		
		stage.canvas.onmouseout = fl_MouseOutHandler_23;
		
		  function fl_MouseOutHandler_23()
		{
		    _this.an.gotoAndPlay(265);
		
		
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// ramka
	this.instance = new lib.Символ53();
	this.instance.parent = this;
	this.instance.setTransform(320,152.5,1,1,0,0,0,319.5,152);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// logo
	this.instance_1 = new lib.Символ3();
	this.instance_1.parent = this;
	this.instance_1.setTransform(92.4,33.9,1.053,1.053,0,0,0,86.8,32);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// an
	this.an = new lib.Символ5();
	this.an.parent = this;
	this.an.setTransform(130.2,165.7,1.053,1.053,0,0,0,63.4,34.7);

	this.timeline.addTween(cjs.Tween.get(this.an).wait(1));

	// bg
	this.instance_2 = new lib.Символ1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(320.4,153,1.065,1.065,0,0,0,299.9,150.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150.4,-171.5,1578.2,746.6);
// library properties:
lib.properties = {
	width: 640,
	height: 305,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg.jpg?1493293973358", id:"bg"},
		{src:"images/canada_big.png?1493293973358", id:"canada_big"},
		{src:"images/iihf_logo.png?1493293973358", id:"iihf_logo"},
		{src:"images/logo.jpg?1493293973358", id:"logo"},
		{src:"images/maska_01.png?1493293973358", id:"maska_01"},
		{src:"images/maska_02.png?1493293973358", id:"maska_02"},
		{src:"images/maska_03.png?1493293973358", id:"maska_03"},
		{src:"images/maska_05.png?1493293973358", id:"maska_05"},
		{src:"images/maska_06.png?1493293973358", id:"maska_06"},
		{src:"images/maska_07.png?1493293973358", id:"maska_07"},
		{src:"images/pole.png?1493293973358", id:"pole"},
		{src:"images/rus_big.png?1493293973358", id:"rus_big"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;