(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.basket = function() {
	this.initialize(img.basket);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,184,250);


(lib.fonbet2gdfg = function() {
	this.initialize(img.fonbet2gdfg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,760,400);


(lib.hokey = function() {
	this.initialize(img.hokey);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,290,281);


(lib.incentive = function() {
	this.initialize(img.incentive);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,83,74);


(lib.stad = function() {
	this.initialize(img.stad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,86,60);


(lib.stopwatch = function() {
	this.initialize(img.stopwatch);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,56,61);


(lib.t_shirts = function() {
	this.initialize(img.t_shirts);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,199,250);


(lib.time = function() {
	this.initialize(img.time);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,66,67);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.ClipGroup = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A9JI5IAAxxMA6TAAAIAARxg");
	mask.setTransform(186.6,56.9);

	// Слой 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiTDhQglgRgRgfQgTgfgBgsQgCgrANg6QANg2AXgtQAaguAggeQAiggArgRQAsgRAzAAQA1AAAlARQAkARATAfQATAhACArQADAtgNA2QgNA2gXAuQgWAtghAfQggAfguASQgrAQg5AAQg2AAgkgQgAgGh2QgRAKgOARQgOAUgJAUQgLAagEAVQgIAegBAZQgCAZAFARQAGAQANAKQANAJAXAAQAWAAAQgKQARgLANgRQANgSAJgXQAIgXAHgaQAFgZACgYQACgYgFgRQgEgRgNgLQgOgKgXAAQgUAAgPAKg");
	this.shape.setTransform(126,55.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ai7DqQgbAAgGgKQgFgLAFgXIBYl7QAGgWAKgLQALgLAbAAIEjAAQAIAAABADQACACgCALIgSBMQgCAHgDAFQgEADgHAAIjPAAIgOA4IBSAAQApAAAdAJQAaAIARAOQAQAOAHAQQAHAQABASQACAPgDARQgCASgDAJQgHAggTAbQgTAcgaAUQgdAVgeALQggALgiAAgAhOB9IBQAAQAOAAAJgFQAJgEAIgHQAHgHAEgIQAEgKABgGQAFgTgJgMQgJgNgWAAIhQAAg");
	this.shape_1.setTransform(218,55.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AiQDqQgQAAADgOIBRlbIhvAAQgPAAAEgPIARhLQADgMAEgBQADgDAIAAIFfAAQAIAAADADQACACgCALIgSBLQgEAPgNAAIhzAAIhPFbQgCAHgDAEQgDADgLAAg");
	this.shape_2.setTransform(306.3,55.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhoDqQgnAAgXgMQgXgLgKgSQgJgRgBgZQAAgUAFgYIAyjVQAFgYAMgXQAMgWATgTQAUgRAbgLQAbgLAiAAIDFAAQAJAAABADQACACgDALIgRBMQgCAIgDADQgEADgHAAIifAAQgPAAgGAEQgKAEgFAFQgFAFgDAHIgEAOIgHAcICyAAQAIAAACACQACADgDALIgQBEQgDAQgNAAIiyAAIgMAyQgDANACAHQAAAHAFAEQAEAEAIABIAQABICoAAQAJAAABACQACAEgDAKIgRBMQgEAPgMAAg");
	this.shape_3.setTransform(261.8,55.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAjDqQgPAAADgOIApiwIiUAAIgoCwQgCAIgDADQgDADgMAAIhfAAQgPAAADgOIBmm3QADgOAQAAIBfAAQALAAACADQABADgBAIIglCeICTAAIAlieQADgOAQAAIBeAAQAMAAABADQACACgCAJIhmG3QgCAIgDADQgDADgLAAg");
	this.shape_4.setTransform(172.9,55.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhoDqQgPAAADgOIAFgVQhfgKgmg0QgmgzAUhWQAJglAWgkQAXgkAfgaQAhgcAngRQAogSAwgHIADgOQAEgOAOAAIBfAAQALAAACADQABADgBAIIgDAOQBcANApAzQApA0gUBVQgKArgWAiQgXAkggAaQghAbgoAQQgqARgvAFIgEAUQgCAIgDADQgDADgLAAgAhMhcQgQALgNAQQgNAQgHAPQgIAPgDAPQgFARgBAUQAAATAFANQAFAOAMALQALAJAUAFIAyjUQgUAEgRAMgAAjBnQAagHARgLQASgMAMgOQAOgPAHgRQAIgRADgOQADgOABgRQAAgRgGgOQgFgOgNgMQgMgKgXgHg");
	this.shape_5.setTransform(73.8,55.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#D62A32").s().p("A7vI5QglAAgagbQgbgaAAgmIAAu7QAAgmAbgaQAagbAlAAMA3fAAAQAlAAAbAbQAaAaAAAmIAAO7QAAAmgaAaQgbAbglAAg");
	this.shape_6.setTransform(186.6,56.9);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup, new cjs.Rectangle(0,0,373.1,113.8), null);


(lib.Символ43 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EhJzApwMAAAhTfMCTnAAAMAAABTfg");
	this.shape.setTransform(472.4,267.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ43, new cjs.Rectangle(0,0,944.8,534.4), null);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJYBCQgRgKgIgRQgJgRAAgWQAAgVAJgRQAIgRARgKQAQgKAWAAQAWAAAQAKQARAKAJARQAIARABAVQgBAWgIARQgJARgRAKQgQAKgWAAQgWAAgQgKgAJhgzQgLAIgHANQgHAOAAAQQAAARAHAOQAHANALAIQAMAHARABQAQgBANgHQALgIAIgNQAGgOAAgRQAAgQgGgOQgIgNgLgIQgNgHgQgBQgRABgMAHgAAtBCQgRgJgKgRQgKgRAAgXQAAgWAKgRQAKgRARgJQARgKAVAAQANAAALAEQAKAEAIAGQAIAHAGAIIgQAJQgGgKgKgGQgLgFgNgBQgQABgMAHQgNAIgIANQgHANAAARQAAARAHAOQAIANANAIQAMAHAQABQANgBALgFQAKgGAGgKIAQAJQgJANgNAIQgOAIgUAAQgVAAgRgKgAohBCQgQgJgLgRQgKgRABgXQgBgWAKgRQALgRAQgJQARgKAVAAQAOAAAKAEQAKAEAIAGQAJAHAGAIIgQAJQgGgKgLgGQgKgFgOgBQgPABgNAHQgNAIgHANQgIANAAARQAAARAIAOQAHANANAIQANAHAPABQAOgBAKgFQALgGAGgKIAQAJQgJANgOAIQgOAIgUAAQgVAAgRgKgAM9BJIg4hCIgPARIAAAxIgSAAIAAiRIASAAIAABKIBBhKIAXAAIg9BFIBCBMgAGxBJIAAiRIBBAAQANAAAJAEQAJAFAFAIQAFAJAAALQAAAJgEAHQgDAHgGAFQgGAEgGACQAHABAHAEQAGAFAEAIQAEAIAAAJQAAAMgFAIQgFAJgJAFQgKAFgOAAgAHDA5IAtAAQANAAAHgHQAHgHAAgLQAAgHgDgGQgDgGgGgDQgGgDgJgBIgtAAgAHDgJIAsAAQANAAAGgHQAGgGAAgKQAAgLgGgGQgGgHgNAAIgsAAgAGIBJIgMggIhJAAIgOAgIgVAAIA8iRIAWAAIA8CRgAE3AYIA/AAIgfhOgADHBJIAAiBIgvAAIAAgQIBvAAIAAAQIguAAIAACBgAiEBJIAAiBIguAAIAAgQIBvAAIAAAQIguAAIAACBgAklBJIAAiRIBhAAIAAAQIhPAAIAAAvIBNAAIAAAPIhNAAIAAAzIBPAAIAAAQgAlaBJIAAg/IgQADQgIACgLAAQgRAAgMgGQgLgHgFgKQgGgLABgPIAAgmIASAAIAAAmQgBARAJAIQAJAJAQAAQAKAAAIgCIAQgDIAAhDIATAAIAACRgApoBJIgNggIhJAAIgNAgIgVAAIA7iRIAXAAIA7CRgAq5AYIA+AAIgehOgAtSBJIAAiRIA7AAQAPAAAKAGQAKAGAGAKQAFAKAAAMQAAAMgGAKQgEAJgLAGQgKAGgPAAIgpAAIAAA6gAtAAAIAnAAQANgBAIgHQAIgIAAgMQAAgNgIgHQgIgIgNAAIgnAAg");
	this.shape.setTransform(88.9,37.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D51023").s().p("AkTBTQgRgJgKgSQgKgRAAgWQAAgVAKgRQAKgRARgJQARgKAWAAQAXAAARAKQARAJAKARQAKARAAAVQAAAWgKARQgKASgRAJQgRAKgXAAQgWAAgRgKgAkDgYQgKAHgGAKQgFALAAANQAAAOAFALQAGALAKAGQAKAHANgBQAOABAKgHQAKgGAFgLQAGgLAAgOQAAgNgGgLQgFgKgKgHQgKgGgOAAQgNAAgKAGgALtBaIAAhhIhGBhIgeAAIAAiRIAgAAIAABdIBEhdIAgAAIAACRgAJNBaIAAiRIAgAAIAACRgAHLBaIAAiRIAfAAIAAA0IAlAAQAQAAALAFQALAHAGAKQAGALAAANQAAANgGALQgGALgLAGQgLAGgQAAgAHqA/IAhAAQAKAAAGgFQAGgGAAgJQAAgJgGgGQgGgEgKAAIghAAgAGOBaIAAg9IhFAAIAAA9IgfAAIAAiRIAfAAIAAA4IBFAAIAAg4IAgAAIAACRgADtBaIAAg9IhFAAIAAA9IgfAAIAAiRIAfAAIAAA4IBFAAIAAg4IAgAAIAACRgAAIBaIAAiRIBoAAIAAAbIhIAAIAAAeIBHAAIAAAcIhHAAIAAAhIBIAAIAAAbgAiJBaIAAiRIBNAAQAOAAAKAFQAJAFAFAJQAFAIAAAKQAAAJgEAIQgDAFgGAFQgGAEgHACQAIABAHAFQAGAFAEAIQADAIABAJQAAALgFAJQgFAJgKAFQgJAGgOgBgAhpA/IAoAAQAJABAFgFQAFgEAAgJQAAgHgFgFQgFgEgJgBIgoAAgAhpACIAnAAQAIABAEgEQAFgFAAgGQAAgIgFgEQgEgEgIAAIgnAAgAluBaIAAg9IhFAAIAAA9IgfAAIAAiRIAfAAIAAA4IBFAAIAAg4IAgAAIAACRgApQBaIAAiRIBoAAIAAAbIhIAAIAAB2gAqMBaIAAhlIgpBlIgOAAIgphlIAABlIggAAIAAiRIAsAAIAkBYIAjhYIAsAAIAACRgAK1hDQgKgFgHgKIANgKQAEAHAHADQAGAEAJAAQAIAAAHgEQAHgDAEgHIANAKQgHAKgKAFQgKAFgMAAQgMAAgKgFg");
	this.shape_1.setTransform(88.2,13.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ41, new cjs.Rectangle(0,0,176.4,53.6), null);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQBYIAAgbIhtAAIAAAbIgTAAIAAgqQAHAAAFgDQAFgBAFgHQADgFAEgMQADgLACgSIAJhJIBaAAIAACAIANAAIAAAsgAHEgKQgDAWgGANQgFAOgIAFIBUAAIAAhwIg3AAgAjXBYIAAgbIhtAAIAAAbIgTAAIAAgqQAHAAAFgDQAFgBAFgHQADgFAEgMQADgLACgSIAJhJIBaAAIAACAIANAAIAAAsgAkjgKQgDAWgGANQgFAOgIAFIBUAAIAAhwIg3AAgAJZA2QgRgJgKgSQgKgQAAgWQAAgXAKgRQAKgRARgJQARgKAVAAQANAAAKAEQALAEAIAGQAIAHAGAIIgQAJQgGgKgLgGQgKgFgNgBQgQAAgNAIQgNAHgHAOQgHANgBASQABAQAHANQAHAOANAIQANAHAQABQANgBAKgFQALgHAGgJIAQAIQgJAOgOAHQgOAIgTAAQgVAAgRgJgAhVA2QgRgJgKgSQgKgQAAgWQAAgXAKgRQAKgRARgJQARgKAVAAQANAAAKAEQALAEAIAGQAHAHAGAIIgPAJQgGgKgLgGQgKgFgNgBQgQAAgNAIQgNAHgHAOQgHANgBASQABAQAHANQAHAOANAIQANAHAQABQANgBAKgFQALgHAGgJIAPAIQgIAOgOAHQgOAIgTAAQgVAAgRgJgAnYA1QgRgKgJgRQgJgQAAgVQAAgWAJgRQAJgRARgKQAQgKAWAAQAWAAAQAKQAQAKAJARQAJARABAWQgBAVgJAQQgJARgQAKQgQAKgWAAQgWAAgQgKgAnPg/QgMAHgGAOQgHAOAAARQAAAQAHANQAGANAMAJQAMAHARABQAQgBAMgHQAMgJAHgNQAHgNAAgQQAAgRgHgOQgHgOgMgHQgMgIgQAAQgRAAgMAIgANLA9IAAiRIBCAAQANgBAJAFQAJAFAFAIQAFAJAAALQAAAJgEAHQgDAHgGAEQgGAFgHACQAIAAAHAGQAGAFAEAHQAEAIAAAJQAAAMgFAIQgFAJgKAFQgJAFgOAAgANeAsIAtAAQANAAAHgGQAHgHAAgMQAAgGgDgGQgDgGgGgCQgGgDgJgBIgtAAgANegVIAsAAQAMgBAHgGQAGgHAAgKQAAgKgGgHQgHgGgMAAIgsAAgALyA9IAAiBIguAAIAAgQIBvAAIAAAQIguAAIAACBgAEdA9IAAiRIBhAAIAAAQIhOAAIAAAvIBMAAIAAAQIhMAAIAAAxIBOAAIAAARgACcA9IAAiRIA7AAQAPAAAKAFQALAGAFAKQAFALAAAMQAAALgFAKQgFAKgLAHQgKAEgPABIgoAAIAAA6gACvgMIAmAAQANgBAIgHQAIgIAAgMQAAgNgIgIQgIgHgNAAIgmAAgABDA9IAAiBIguAAIAAgQIBvAAIAAAQIguAAIAACBgAqAA9IAAiRIBCAAQANgBAJAFQAJAFAFAIQAFAJAAALQAAAJgEAHQgDAHgGAEQgGAFgHACQAIAAAHAGQAGAFAEAHQAEAIAAAJQAAAMgFAIQgFAJgKAFQgJAFgOAAgAptAsIAtAAQANAAAHgGQAHgHAAgMQAAgGgDgGQgDgGgGgCQgGgDgJgBIgtAAgAptgVIAsAAQAMgBAHgGQAGgHAAgKQAAgKgGgHQgHgGgMAAIgsAAgAq0A9IAAiRIASAAIAACRgAstA9IAAiRIASAAIAAA5IApAAQAPAAAKAHQAKAFAFALQAGAIAAAMQAAANgFAKQgGAKgKAGQgKAGgPAAgAsbAsIAnAAQANAAAIgHQAIgIAAgNQAAgMgIgGQgIgIgNAAIgnAAgAu4A9IAAiRIBCAAQANgBAJAFQAJAFAFAIQAFAJAAALQAAAJgEAHQgDAHgGAEQgGAFgHACQAIAAAHAGQAGAFAEAHQAEAIAAAJQAAAMgFAIQgFAJgKAFQgJAFgOAAgAulAsIAtAAQANAAAHgGQAHgHAAgMQAAgGgDgGQgDgGgGgCQgGgDgJgBIgtAAgAulgVIAsAAQAMgBAHgGQAGgHAAgKQAAgKgGgHQgHgGgMAAIgsAAg");
	this.shape.setTransform(99,39);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D51023").s().p("AitBTQgRgJgKgRQgLgRAAgXQAAgWALgQQAKgSARgJQASgJAWAAQAQAAAMAEQAMAGAIAIQAJAIAEAKIgbAMQgEgJgJgGQgJgGgMAAQgNAAgKAGQgLAHgGAKQgGALAAANQAAAOAGALQAGALALAGQAKAHANgBQAMAAAJgGQAJgGAEgJIAbANQgEAKgJAHQgIAJgMAFQgMAFgQAAQgWAAgSgKgAH1BaIAAhhIhGBhIgdAAIAAiRIAfAAIAABdIBEhdIAgAAIAACRgAFVBaIAAiRIAgAAIAACRgADTBaIAAiRIAfAAIAAA0IAlAAQARAAAKAFQAMAHAFAKQAGALAAANQAAANgGALQgFALgMAGQgKAGgRAAgADyA/IAiAAQAJAAAGgFQAGgGAAgJQAAgJgGgGQgGgEgJAAIgiAAgABJBaIAAiRIBFAAQAQAAALAHQALAFAGAMQAGAKAAANQAAAMgGALQgGALgLAGQgLAGgQAAIglAAIAAA0gABpALIAhAAQAKAAAFgFQAHgGAAgIQAAgJgHgFQgFgGgKAAIghAAgAgTBaIAAh2IgrAAIAAgbIB0AAIAAAbIgqAAIAAB2gAkIBaIAAiRIAfAAIAACRgAmLBaIAAiRIAgAAIAAA0IAlAAQAQAAALAFQALAHAGAKQAGALgBANQABANgGALQgGALgLAGQgLAGgQAAgAlrA/IAhAAQAKAAAFgFQAHgGAAgJQAAgJgHgGQgFgEgKAAIghAAgAoUBaIAAiRIBrAAIAAAbIhLAAIAAAbIAmAAQAPgBALAGQAKAGAHAKQAFALAAANQAAAMgFALQgGALgLAGQgLAGgPAAgAn0A/IAhAAQAJAAAGgFQAGgFAAgJQAAgJgGgFQgGgFgJAAIghAAgAG+hDQgLgFgGgKIAMgKQAFAHAGADQAHAEAIAAQAJAAAGgEQAHgDAEgHIANAKQgHAKgKAFQgKAFgMAAQgLAAgKgFg");
	this.shape_1.setTransform(98.8,13.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ40, new cjs.Rectangle(0,0,197.6,53.6), null);


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACnBYIAAgbIh2AAIAAiRIATAAIAACAIBWAAIAAiAIASAAIAACAIANAAIAAAsgApVA3QgNgHgKgOIAQgIQAHAJAKAHQALAFAMABQAPgBAMgGQAMgHAIgMQAHgMACgPIhRAAIAAgQIBQAAQgCgPgHgLQgIgLgLgHQgMgFgPgBQgMABgLAFQgKAGgHAKIgPgJQAFgIAIgHQAJgGAJgEQALgEANAAQAVAAARAKQASAJAJARQAKARAAAXQAAAWgKAQQgJASgSAJQgRAJgVAAQgUAAgNgIgArsA1QgRgKgJgRQgJgQAAgVQAAgWAJgRQAJgRARgKQAPgKAXAAQAVAAAQAKQARAKAJARQAJARABAWQgBAVgJAQQgJARgRAKQgQAKgVAAQgXAAgPgKgArjg/QgMAHgGAOQgHAOAAARQAAAQAHANQAGANAMAJQAMAHARABQAQgBAMgHQAMgJAHgNQAGgNABgQQgBgRgGgOQgHgOgMgHQgMgIgQAAQgRAAgMAIgAN9A9IAAiRIARAAIAACRgAMEA9IAAiRIASAAIAAA5IAoAAQAPAAALAHQAKAFAFALQAGAIgBAMQAAANgEAKQgGAKgKAGQgLAGgPAAgAMWAsIAnAAQANAAAHgHQAJgIgBgNQABgMgJgGQgHgIgNAAIgnAAgAKrA9IAAiBIgvAAIAAgQIBwAAIAAAQIgvAAIAACBgAJSA9IAAhCIhWAAIAABCIgTAAIAAiRIATAAIAAA/IBWAAIAAg/IASAAIAACRgAFsA9IAAiRIBhAAIAAAQIhOAAIAAAvIBNAAIAAAQIhNAAIAAAxIBOAAIAAARgAE4A9IAAh0IhWB0IgRAAIAAiRIASAAIAABxIBUhxIATAAIAACRgAgCA9IAAh0IhWB0IgRAAIAAiRIASAAIAABxIBUhxIASAAIAACRgAjdA9IAAgPQgVgBgPgIQgPgHgIgNQgIgNAAgPQAAgQAIgNQAIgNAPgIQAPgIAVgBIAAgOIASAAIAAAOQAWABAPAIQAPAIAJANQAIANAAAQQAAAPgIANQgJANgPAHQgPAIgWABIAAAPgAjLAeQAYgCANgMQANgLAAgQQAAgSgNgLQgNgMgYgCgAkBgoQgNALAAASQAAAQANALQANAMAXACIAAhUQgXACgNAMgAmOA9IAAgPQgVgBgQgIQgPgHgIgNQgIgNAAgPQAAgQAIgNQAIgNAPgIQAQgIAVgBIAAgOIASAAIAAAOQAVABAQAIQAPAIAIANQAIANAAAQQAAAPgIANQgIANgPAHQgQAIgVABIAAAPgAl8AeQAYgCANgMQANgLgBgQQABgSgNgLQgNgMgYgCgAmzgoQgMALAAASQAAAQAMALQANAMAYACIAAhUQgYACgNAMgAs0A9Ig5hBIgOAQIAAAxIgSAAIAAiRIASAAIAABLIBBhLIAWAAIg8BFIBCBMg");
	this.shape.setTransform(94.8,39);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D51023").s().p("AgMBCQgRgKgKgRQgKgRAAgWQAAgVAKgRQAKgRARgKQARgKAWAAQAWAAASAKQARAKAKARQAJARABAVQgBAWgJARQgKARgRAKQgSAKgWAAQgWAAgRgKgAADgpQgJAGgFALQgGALAAANQAAAOAGALQAFAKAJAHQAKAGAOAAQANAAAKgGQAKgHAGgKQAFgLAAgOQAAgNgFgLQgGgLgKgGQgKgGgNAAQgOAAgKAGgAihBCQgSgJgKgRQgLgRAAgXQAAgWALgRQAKgRASgJQARgKAWAAQAQAAAMAFQAMAFAIAJQAJAIAFAJIgbANQgFgJgJgGQgJgGgMAAQgNAAgKAGQgLAGgGALQgGALAAANQAAAOAGALQAGALALAGQAKAGANAAQAMAAAJgGQAJgGAFgJIAbANQgFAJgJAIQgIAIgMAGQgMAFgQAAQgWAAgRgKgAGqBJIAAiRIBoAAIAAAbIhIAAIAAAfIBHAAIAAAbIhHAAIAAAhIBIAAIAAAbgAFuBJIAAhhIhGBhIgeAAIAAiRIAfAAIAABdIBEhdIAgAAIAACRgADVBJIgtg7IgLAOIAAAtIgfAAIAAiRIAfAAIAABBIA0hBIAmAAIg6BEIA+BNgAj9BJIAAiRIAgAAIAACRgAl/BJIAAiRIAfAAIAAA0IAlAAQAQAAALAGQALAHAGAJQAGALAAANQAAANgGALQgGAKgLAHQgLAGgQAAgAlgAuIAhAAQAKAAAGgGQAGgFAAgJQAAgJgGgGQgGgFgKAAIghAAgAoRBJIAAiRIBNAAQAOAAAJAFQAKAFAEAJQAFAIAAAKQAAAJgDAHQgEAHgFAFQgGAEgHACQAIABAGAEQAGAFAEAIQAEAHAAAKQAAALgFAJQgFAJgJAFQgKAFgOAAgAnyAuIAoAAQAJAAAFgEQAFgFAAgIQAAgHgFgFQgEgFgKAAIgoAAgAnygOIAnAAQAIAAAFgEQAEgFAAgHQAAgHgEgEQgFgFgIAAIgnAAg");
	this.shape_1.setTransform(95.1,14.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ39, new cjs.Rectangle(0,0,189.7,53.6), null);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AlKBSQgRgKgJgRQgIgRgBgWQABgVAIgRQAJgQARgLQAQgKAWAAQAWAAAQAKQARALAIAQQAKARAAAVQAAAWgKARQgIARgRAKQgQAKgWAAQgWAAgQgKgAlBgiQgMAHgGANQgHAOAAAQQAAARAHAOQAGANAMAIQANAHAQABQARgBAMgHQALgIAIgNQAGgOAAgRQAAgQgGgOQgIgNgLgHQgMgIgRAAQgQAAgNAIgAncBTQgRgKgKgRQgKgRAAgXQAAgWAKgQQAKgSARgJQARgJAVgBQANAAALAEQAKAEAIAHQAIAGAGAIIgPAJQgHgJgKgHQgLgFgNAAQgQAAgNAIQgMAHgIANQgHAOAAAQQAAARAHAOQAIANAMAIQANAHAQABQANAAALgGQAKgGAHgJIAPAIQgJANgNAIQgPAIgTAAQgVAAgRgJgAHwBaIAAh0IhVB0IgSAAIAAiSIASAAIAABxIBVhxIASAAIAACSgAFUBaIAAh0IhWB0IgSAAIAAiSIATAAIAABxIBVhxIASAAIAACSgACTBaIAAiCIguAAIAAgQIBwAAIAAAQIgvAAIAACCgAA6BaIAAiSIASAAIAACSgAg+BaIAAiSIATAAIAAA5IApAAQAOAAAJAGQALAGAFAKQAGAKAAAMQgBAMgFAKQgFAKgLAHQgJAFgOABgAgrBJIAmAAQAMAAAJgHQAHgIABgNQgBgNgHgHQgJgIgMABIgmAAgAi+BaIAAiSIBfAAIAAAQIhNAAIAAApIAoAAQAPAAALAGQAKAGAFAKQAGAKgBAMQAAAMgEAKQgGAKgKAHQgLAFgPABgAisBJIAmAAQAOAAAHgHQAJgIgBgNQABgNgJgHQgHgIgOABIgmAAgAGwhGQgKgFgHgJIAIgHQAFAHAIAFQAIAEAJAAQAKAAAIgEQAHgFAGgHIAIAHQgHAJgKAFQgJAGgNgBQgMABgJgGg");
	this.shape.setTransform(74.2,36.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D51023").s().p("AJUBCQgRgKgKgRQgJgRgBgWQABgVAJgRQAKgRARgKQASgKAWAAQAWAAASAKQARAKAKARQAJARABAVQgBAWgJARQgKARgRAKQgSAKgWAAQgWAAgSgKgAJkgpQgKAGgFALQgFALAAANQAAAOAFALQAFAKAKAHQAKAGAOAAQAOAAAJgGQAKgHAGgKQAFgLABgOQgBgNgFgLQgGgLgKgGQgJgGgOAAQgOAAgKAGgACtBCQgRgJgLgRQgKgRAAgXQAAgWAKgRQALgRARgJQASgKAWAAQAQAAAMAFQAMAFAIAJQAIAIAGAJIgbANQgFgJgKgGQgJgGgLAAQgOAAgKAGQgKAGgGALQgGALAAANQAAAOAGALQAGALAKAGQAKAGAOAAQALAAAJgGQAKgGAFgJIAbANQgGAJgIAIQgIAIgMAGQgMAFgQAAQgWAAgSgKgAlNBCQgRgKgKgRQgKgRAAgWQAAgVAKgRQAKgRARgKQASgKAVAAQAXAAASAKQAQAKALARQAJARAAAVQAAAWgJARQgLARgQAKQgSAKgXAAQgVAAgSgKgAk9gpQgKAGgGALQgFALAAANQAAAOAFALQAGAKAKAHQAKAGANAAQAOAAAKgGQAKgHAGgKQAFgLAAgOQAAgNgFgLQgGgLgKgGQgKgGgOAAQgNAAgKAGgAGlBJIAAiRIBMAAQAOAAAKAFQAJAFAFAJQAFAIAAAKQAAAJgDAHQgEAHgFAFQgHAEgHACQAJABAGAEQAGAFAEAIQAEAHAAAKQAAALgFAJQgFAJgKAFQgJAFgOAAgAHEAuIAoAAQAJAAAFgEQAFgFAAgIQAAgHgFgFQgEgFgKAAIgoAAgAHEgOIAnAAQAIAAAEgEQAFgFAAgHQAAgHgFgEQgEgFgIAAIgnAAgAFHBJIAAh2IgrAAIAAgbIB1AAIAAAbIgrAAIAAB2gAAOBJIAAiRIBnAAIAAAbIhIAAIAAAfIBHAAIAAAbIhHAAIAAAhIBIAAIAAAbgAgmBJIgsg7IgHAIIAAAzIgfAAIAAgzIgHgIIgsA7IgmAAIA+hNIg7hEIAnAAIAvA6IAAg6IAfAAIAAA6IAug6IAoAAIg7BEIA+BNgAmoBJIAAg9IhFAAIAAA9IgfAAIAAiRIAfAAIAAA5IBFAAIAAg5IAgAAIAACRgApJBJIAAhlIgoBlIgOAAIgqhlIAABlIgfAAIAAiRIAsAAIAkBXIAjhXIAsAAIAACRg");
	this.shape_1.setTransform(74.9,14.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ38, new cjs.Rectangle(0,0,149,53.6), null);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.incentive();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ37, new cjs.Rectangle(0,0,83,74), null);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.stad();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ36, new cjs.Rectangle(0,0,86,60), null);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.stopwatch();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ35, new cjs.Rectangle(0,0,56,61), null);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.time();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ34, new cjs.Rectangle(0,0,66,67), null);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D62A32").s().p("AgcA6IgFgBIACgLIAEABIADAAQAEAAADgCQADgCADgFIAFgMIgjhUIAOAAIAbBEIAchEIAOAAIgqBkQgDAJgGAEQgGADgIABIgFgBg");
	this.shape.setTransform(149.5,22.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D62A32").s().p("AAUAqIgdgmIgOAOIAAAYIgNAAIAAhTIANAAIAAAsIArgsIAQAAIgkAmIAlAtg");
	this.shape_1.setTransform(141.4,20.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#D62A32").s().p("AgiAqIAAhTIAtAAQAKABAHAFQAGAGAAAKQgBAHgDAFQgEAFgGACQAHABAEAFQAEAGABAHQAAAKgHAHQgGAGgMAAgAgWAeIAfAAQAGAAAEgDQADgDAAgGQAAgGgDgDQgEgEgGAAIgfAAgAgWgGIAeAAQAHAAADgDQACgDAAgFQAAgGgCgDQgEgDgGAAIgeAAg");
	this.shape_2.setTransform(131.7,20.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#D62A32").s().p("AgTApQgGgDgFgHQgEgGAAgJQAAgJAEgGQAFgFAGgDQAHgDAHAAQAIAAAHACQAHADAFAFIAAgOQAAgIgGgFQgGgEgJAAQgHAAgGACQgGADgGAGIgGgJQAHgHAIgDQAIgEAKAAQAIAAAIADQAHADAEAGQAFAGAAAKIAAA5IgNAAIAAgKQgFAGgHADQgHADgIAAQgHAAgHgDgAgPADQgFAFgBAIQABAIAFAFQAGAFAJAAQAGAAAGgCQAGgDAEgFIAAgQQgEgFgGgCQgGgCgGAAQgJAAgGAEg");
	this.shape_3.setTransform(122.1,20.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#D62A32").s().p("AgGAqIAAhHIgYAAIAAgMIA9AAIAAAMIgZAAIAABHg");
	this.shape_4.setTransform(114.3,20.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#D62A32").s().p("AgPAmQgKgGgFgKQgFgKAAgMQAAgLAFgKQAFgKAKgGQAJgGAMAAQALAAAHAEQAHAEAFAHIgJAIQgEgGgFgDQgFgCgHAAQgIAAgGAEQgHAEgDAHQgEAIAAAIQAAAJAEAIQADAHAHAEQAGAEAIAAQAHAAAFgCQAFgDAEgGIAJAIQgFAHgHAEQgHAEgLAAQgMAAgJgGg");
	this.shape_5.setTransform(106.7,20.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#D62A32").s().p("AgiAqIAAhTIANAAIAAAhIAeAAQAJAAAFADQAGAEADAEQADAGAAAHQAAAHgDAGQgDAGgGADQgGAEgIAAgAgVAeIAdAAQAHAAADgEQAEgDAAgHQAAgGgEgEQgDgEgHAAIgdAAg");
	this.shape_6.setTransform(93.6,20.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#D62A32").s().p("AgGAqIAAhHIgYAAIAAgMIA9AAIAAAMIgZAAIAABHg");
	this.shape_7.setTransform(85.3,20.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#D62A32").s().p("AgTApQgGgDgFgHQgEgGAAgJQAAgJAEgGQAFgFAGgDQAHgDAHAAQAIAAAHACQAHADAFAFIAAgOQAAgIgGgFQgGgEgJAAQgHAAgGACQgGADgGAGIgGgJQAHgHAIgDQAIgEAKAAQAIAAAIADQAHADAEAGQAFAGAAAKIAAA5IgNAAIAAgKQgFAGgHADQgHADgIAAQgHAAgHgDgAgPADQgFAFgBAIQABAIAFAFQAGAFAJAAQAGAAAGgCQAGgDAEgFIAAgQQgEgFgGgCQgGgCgGAAQgJAAgGAEg");
	this.shape_8.setTransform(77.1,20.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#D62A32").s().p("AgnAgQAGAAAEgIQAEgHACgSIAGgpIA5AAIAABTIgNAAIAAhHIghAAIgEAeQgCAPgDAKQgEAJgGAFQgGAEgIAAg");
	this.shape_9.setTransform(67.5,21);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#D62A32").s().p("AgTAmQgKgFgFgKQgGgKAAgNQAAgLAGgKQAFgKAJgGQAJgGAMAAQAMAAAJAGQAJAGAFAKQAEAKABAMIAAADIhDAAQABAIADAHQAEAGAHAEQAGAEAIAAQAHAAAHgDQAHgCAFgFIAGAIQgGAGgJADQgIAEgKAAQgMAAgJgGgAAcgEQAAgHgDgGQgDgGgGgFQgGgEgKAAQgIAAgGAEQgFAFgEAGQgDAGAAAHIA2AAIAAAAg");
	this.shape_10.setTransform(58.4,20.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#D62A32").s().p("AAfA0IAAgVIg+AAIAAAVIgNAAIAAgfQAFgBADgDQACgDACgHQADgGACgMIAFgoIA5AAIAABHIAKAAIAAAggAgPgJQgBALgDAHQgDAHgEAEIAwAAIAAg8IggAAg");
	this.shape_11.setTransform(48.6,22);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#D62A32").s().p("AgWA0QgNgHgIgOQgHgNgBgSQABgRAHgNQAIgOANgHQAOgIAQAAQAKAAAIAEQAIACAGAGQAGAFAGAGIgNAHQgFgHgIgFQgIgFgKABQgMgBgKAGQgKAGgGAKQgFALgBANQABANAFALQAGALAKAFQAKAHAMgBQAKAAAIgEQAIgFAFgHIANAHQgIAJgKAHQgLAHgPAAQgQAAgOgIg");
	this.shape_12.setTransform(38.2,19.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AufDSQgjAAAAgjIAAldQAAgjAjAAIc/AAQAjAAAAAjIAAFdQAAAjgjAAg");
	this.shape_13.setTransform(93.3,20.3,0.968,0.968);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ25, new cjs.Rectangle(0,0,186.5,40.7), null);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","rgba(255,255,255,0)"],[0,0.478,1],-13.8,0,13.8,0).s().p("AiqJrIAAzVIFVAAIAATVg");
	this.shape.setTransform(17.1,61.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ18, new cjs.Rectangle(0,0,34.3,123.8), null);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgkBKIgGgBIACgPIAFABIAEABQAGAAAEgDQADgCADgHIAHgQIgshqIASAAIAiBWIAjhWIASAAIg1B/QgEAMgIAEQgIAGgKgBIgGAAg");
	this.shape.setTransform(151.5,19.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAaA1IgmgwIgRARIAAAfIgRAAIAAhpIARAAIAAA3IA3g3IAVAAIgvAwIAvA5g");
	this.shape_1.setTransform(141.1,17);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgsA1IAAhpIA5AAQAOAAAIAIQAIAHAAAMQAAAKgFAGQgFAGgHACQAIABAGAIQAFAHAAAJQAAANgIAIQgIAIgPAAgAgcAmIAnAAQAIAAAFgEQAEgEAAgIQAAgGgEgFQgEgFgJgBIgnAAgAgcgIIAmAAQAIAAAEgEQAEgEAAgHQAAgGgEgEQgEgEgIAAIgmAAg");
	this.shape_2.setTransform(128.8,17);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgYA0QgIgEgGgIQgGgIABgLQgBgMAGgIQAGgHAIgEQAJgDAJAAQAJAAAKADQAJAEAGAGIAAgSQgBgLgGgFQgIgGgMAAQgJAAgHADQgIAEgHAHIgIgLQAIgJALgEQALgFAMAAQALAAAJAEQAJAEAGAIQAGAHgBANIAABIIgQAAIAAgMQgGAHgJAEQgKAEgJAAQgJAAgJgEgAgTAEQgIAGAAALQAAAKAIAGQAHAHALAAQAJAAAHgDQAIgEAFgGIAAgUQgFgHgIgDQgHgCgJAAQgLAAgHAFg");
	this.shape_3.setTransform(116.6,16.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgHA1IAAhaIgfAAIAAgPIBNAAIAAAPIgfAAIAABag");
	this.shape_4.setTransform(106.6,17);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgUAwQgMgHgHgMQgGgNAAgQQAAgPAGgMQAHgNAMgHQAMgHAPgBQAOABAJAFQAKAFAGAIIgLAKQgGgHgGgEQgHgDgIAAQgKAAgJAGQgIAFgEAJQgFAJAAALQAAAMAFAJQAEAJAIAGQAJAFAKAAQAIAAAHgDQAGgEAGgHIALAKQgGAIgKAGQgJAFgOAAQgPAAgMgIg");
	this.shape_5.setTransform(97,16.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgsA1IAAhpIARAAIAAApIAnAAQALAAAHAEQAHAFAEAGQAEAHAAAJQAAAJgEAIQgEAHgHAEQgIAFgKAAgAgbAmIAlAAQAJAAAEgEQAFgGAAgIQAAgHgFgFQgEgGgJAAIglAAg");
	this.shape_6.setTransform(80.3,17);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgHA1IAAhaIgfAAIAAgPIBNAAIAAAPIgfAAIAABag");
	this.shape_7.setTransform(69.7,17);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgYA0QgJgEgFgIQgFgIAAgLQAAgMAFgIQAFgHAJgEQAIgDAJAAQALAAAIADQAKAEAGAGIAAgSQAAgLgIgFQgHgGgMAAQgIAAgJADQgIAEgHAHIgHgLQAJgJAKgEQAKgFAMAAQALAAAKAEQAJAEAGAIQAFAHABANIAABIIgRAAIAAgMQgGAHgKAEQgIAEgLAAQgJAAgIgEgAgTAEQgHAGAAALQAAAKAHAGQAHAHAMAAQAHAAAJgDQAHgEAFgGIAAgUQgFgHgHgDQgJgCgHAAQgMAAgHAFg");
	this.shape_8.setTransform(59.3,16.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgxApQAHAAAFgKQAEgKAEgWIAHg0IBJAAIAABpIgRAAIAAhbIgqAAIgFAnQgCAUgFAMQgEAMgIAFQgIAFgJAAg");
	this.shape_9.setTransform(47.1,17.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgZAxQgMgHgHgNQgHgMAAgRQAAgOAHgNQAHgNALgHQAMgHAOgBQARABALAHQALAIAGAMQAGANABAPIAAAFIhWAAQABAKAFAIQAFAIAIAFQAIAFALAAQAJAAAJgDQAIgEAGgGIAIALQgIAHgKAFQgLAEgNAAQgPAAgMgHgAAjgGQAAgIgEgIQgDgIgIgFQgIgGgMAAQgKAAgIAGQgHAFgEAIQgEAIgBAIIBFAAIAAAAg");
	this.shape_10.setTransform(35.4,16.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAoBCIAAgbIhPAAIAAAbIgRAAIAAgoQAFgBAEgEQAEgDADgIIAFgYIAGg0IBJAAIAABbIANAAIAAApgAgTgMQgCAPgEAIQgEAKgFAEIA+AAIAAhMIgqAAg");
	this.shape_11.setTransform(22.9,18.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcBCQgQgJgLgRQgKgRAAgXQAAgWAKgRQALgRAQgJQARgKAUAAQAOAAAKAEQAKAEAIAGQAJAHAGAIIgQAJQgGgKgLgGQgKgFgOgBQgOABgNAHQgNAIgHANQgIANAAARQAAARAIAOQAHANANAIQANAHAOABQAOgBAKgFQALgGAGgKIAQAJQgJANgOAIQgOAIgUAAQgUAAgRgKg");
	this.shape_12.setTransform(9.7,14.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ13, new cjs.Rectangle(0,0,159.1,30.8), null);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag3BWQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBAAIgCgFIAAidIACgFQABAAABgBQAAAAABAAQAAAAABAAQAAAAABAAIBuAAQABAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAABABAAQAAABAAAAQAAABAAAAQABABAAABIAAAdQAAABgBAAQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAQgBAAAAAAQgBABgBAAIhCAAIAAAWIA2AAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQABABAAABQAAAAABABQAAAAAAABQAAAAAAABIAAAdQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAIg2AAIAAAWIBDAAQABAAABABQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQABABAAABIAAAdQAAABgBABQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQgBABgBAAg");
	this.shape.setTransform(99.9,42.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgSBWQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAAAIgCgFIAAh5IgrAAQAAAAgBgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAgBQAAAAAAgBIAAgdIACgFQAAAAABgBQAAAAABAAQAAAAABAAQABAAAAAAICHAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABABAAAAQABABAAAAQAAABAAAAQAAABAAABIAAAdQAAABAAAAQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAIgrAAIAAB5QAAABAAABQAAAAAAABQgBAAAAABQAAAAgBABQAAAAgBAAQAAABAAAAQgBAAgBAAQAAABgBAAg");
	this.shape_1.setTransform(83.7,42.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AggBRQgQgGgNgNQgNgMgHgQQgHgQAAgSQAAgRAHgQQAHgQANgNQANgMAQgGQARgHASAAQAVAAASAIQARAIANAOQAMAOAFAUIAAAEQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAIgGAAIgMAAIgMAAIgJAAIgDgBIgCgCQgFgMgKgGQgJgGgOAAQgMAAgJAGQgKAGgFAKQgFAKAAAMQAAANAFAKQAFAKAKAGQAJAGAMAAQAOAAAKgGQAKgGAFgNIABgDIAEgBIAKAAIAMAAIAKAAIAGAAQABAAAAABQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAABAAAAQgFAUgMAPQgMAOgSAIQgSAIgVAAQgSAAgRgHg");
	this.shape_2.setTransform(65,42.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag3BWQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBAAIgCgFIAAidIACgFQABAAABgBQAAAAABAAQAAAAABAAQAAAAABAAIBuAAQABAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAABIAAAdQAAABAAAAQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAQgBAAAAAAQgBABgBAAIhCAAIAAAWIA2AAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQABABAAABQAAAAAAABQABAAAAABQAAAAAAABIAAAdQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAIg2AAIAAAWIBDAAQABAAABABQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAABIAAAdQAAABAAABQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQgBABgBAAg");
	this.shape_3.setTransform(47.4,42.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA0BWQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBIAAhLIgFAFIgIANIgKAOIgFAIQgEAGgCABIgEAAIgFAAIgGAAIgDAAIgEAAQgDgBgDgGIgGgIIgKgOIgJgNIgDgFIAABLQAAABgBABQAAAAAAABQAAAAAAABQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQgBABgBAAIglAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAIgCgFIAAidIACgFQABAAAAgBQABAAAAAAQABAAAAAAQABAAABAAIAcAAIAFABIAEADIAHAJIAMASIAQAVIAMARIAEAHIAFgHIANgRIAOgVIAOgSIAGgJIAEgDIAFgBIAdAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAABIAACdQAAABAAABQAAAAAAABQgBAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAABgBAAg");
	this.shape_4.setTransform(29.1,42.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAABWIgRAAIgUAAIgRAAIgHAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBAAIgBgEIAAieIABgFQABAAABgBQAAAAABAAQAAAAABAAQAAAAABAAIAFAAIAPAAIARAAIAOAAIAHAAQARgBAOAFQAOAEAJAKQAIAKAAARQAAAHgDAIQgEAHgGAGQgGAGgIACIAAABQAMABAHAEQAJAGAEAIQAEAIABAJQgBAQgHAMQgIALgNAHQgOAGgTAAIgHAAgAgRAtIANAAIAHAAQAIAAAEgEQAEgEABgGQgBgFgEgEQgEgEgHAAIgHAAIgOAAgAgRgQIAFAAIAGAAQAKAAADgFQAFgEAAgGQgBgFgFgEQgFgDgIAAIgEAAIgGAAg");
	this.shape_5.setTransform(10.3,42.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAfBuQAAAAgBAAQgBgBAAAAQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAhRIgFAHIgMASIgOAWIgNAUIgIALQgDAFgDACQgDACgFAAIgbAAQgBAAAAAAQgBgBgBAAQAAAAgBAAQAAgBgBAAIgCgEIAAieIACgFQABAAAAAAQABgBAAAAQABAAABAAQAAAAABAAIAmAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAQABABAAABQAAAAAAABIAABRIA2hRIAEgFQADgBAFAAIAFAAIAKAAIAIAAIAEAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABABAAQAAABAAAAQABABAAABQAAAAAAABIAACeQAAAAAAABQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAgAgehJQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBIAAgXQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQAAAAABAAIBEAAQAAAAABAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAQABABAAAAQAAABAAAAQABABAAABIAAAXIgCAFQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAg");
	this.shape_6.setTransform(150.2,14.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABKBVIgNAAIgNAAIgGAAQgFAAgCgCQgCgBgCgGIgCgEIgDgJIgzAAIgDAJIgCAEQgCAGgCABQgCACgFAAIgGAAIgNAAIgNAAIgIAAQgDAAgBgCQgCgCACgEIAEgLIAIgWIALgeIAMgfIALgeIAIgWIAEgKIADgEQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAIApAAQAAAAABABQABAAAAAAQABAAAAAAQABABAAAAQACACABACIAEAKIAIAXIALAdIAMAfIALAfIAJAWIADAKQACAEgCACQgBACgDAAIgIAAgAANAUIgGgTIgHgUIgFAUIgHATIAZAAIAAAAg");
	this.shape_7.setTransform(131.5,17);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAyBnQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBIAAgdIhXAAIAAAdQAAABAAAAQAAABAAABQAAAAgBABQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAQAAAAgBAAIgmAAQgBAAAAAAQgBAAgBAAQAAAAAAgBQgBAAAAAAIgCgFIAAhAIAAgBIACgEQAAgBABAAQAAAAAAgBQABAAABAAQAAAAABAAIARAAIAFgQIADgPIADgVIABgYIABgXIAAgRIAAgGQAAgBAAAAQAAgBABgBQAAAAAAgBQABAAAAgBQABAAAAAAQABgBAAAAQABAAABAAQAAAAABAAIB2AAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAQABABAAABQAAAAAAABIAAB6IAOAAQABAAAAAAQABAAABAAQAAABABAAQAAAAABABQAAAAAAABQABAAAAAAQAAABAAABQAAAAAAABIAABBQAAABAAAAQAAABAAABQAAAAgBABQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAQAAAAgBAAgAgIghIgDAcIgEARIgEAOIAqAAIAAhWIgdAAIgCAbg");
	this.shape_8.setTransform(110.9,18.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AB1BVIgOAAIgOAAIgGAAQgFAAgCgCIgGgHIgEgGIgIgOIgJgSIgJgRIgPAAIAAA7QAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAIgmAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAg7IgPAAIgJARIgJASIgIAOIgDAGQgDAFgEACQgDACgDAAIgGAAIgPAAIgOAAIgIAAQgDAAgCgCQgCgDACgDIAGgKIAKgSIALgVIAKgTIAGgJIgJgQIgKgUIgKgTIgIgQIgEgHQgBgEABgBQABgCAGAAIAJAAIAQAAIANAAIAGAAIAFABQACACACADIADAHIAHAOIAKASIAKAUIANAAIAAg7QAAAAAAgBQAAAAAAgBQABAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAIAmAAQAAAAABABQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABQAAABABAAQAAABAAAAQAAABAAAAIAAA7IAOAAIAKgUIAJgSIAHgOIADgHIAEgFIAFgBIAHAAIANAAIAPAAIAJAAQAFAAACACQACABgCAEIgEAHIgIAQIgKATIgKAUIgIAQIAGAJIAJATIAMAVIAJASIAGAKQACADgCADQgBACgEAAIgIAAg");
	this.shape_9.setTransform(86,17);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag3BVQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAgBIgDgDIAAifIADgEQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAIBvAAQAAAAABABQAAAAABAAQAAAAABAAQABABAAAAQAAAAABABQAAABAAAAQAAABAAAAQAAABAAAAIAAAeQAAABAAAAQAAABAAABQAAAAAAABQgBAAAAABQAAAAgBAAQgBABAAAAQgBAAAAAAQgBAAAAAAIhDAAIAAAXIA2AAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABIAAAdQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBABQAAAAgBAAQAAAAgBAAIg2AAIAAAXIBEAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAAAQABABAAAAQAAABAAAAQAAABAAAAIAAAfQAAAAAAABQAAAAAAABQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_10.setTransform(64.3,17);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAABVIgQAAIgVAAIgRAAIgHAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQgBAAAAgBIgCgDIAAifIACgEQAAAAABgBQABAAAAAAQABAAAAAAQABgBAAAAIBnAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQAAABABAAQAAABAAAAQAAABAAAAIAAAeQAAABAAAAQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAIg6AAIAAAXIAQAAIAIAAQASAAAOAFQANAGAIALQAHALAAARQAAASgHANQgIAMgNAGQgOAHgSgBIgIAAgAgQAtIANAAIAHAAQAIAAAEgEQAFgEgBgFQABgGgFgDQgEgDgIgBIgGAAIgOAAg");
	this.shape_11.setTransform(48.8,17);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgiBSQgRgIgMgLQgNgMgHgQQgHgRgBgSQABgSAHgPQAHgQANgMQAMgNARgGQAQgIASAAQATAAAQAIQARAGANANQAMAMAIAQQAHAPAAASQAAASgHARQgIAQgMAMQgNALgRAIQgQAGgTABQgSgBgQgGgAgVgmQgKAGgFAKQgGALAAALQAAANAGAJQAFALAKAGQAKAGALAAQAMAAAKgGQAKgGAGgLQAFgJAAgNQAAgLgFgLQgGgKgKgGQgKgGgMAAQgLAAgKAGg");
	this.shape_12.setTransform(30.4,17);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAgBVQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAIAAh7Ig0AAIAAB7QAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAIgmAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQgBAAAAgBIgCgDIAAifIACgEQAAAAABgBQABAAAAAAQABAAAAAAQABgBAAAAICNAAQAAAAABABQABAAAAAAQABAAAAAAQABABAAAAIACAEIAACfIgCADQAAABgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAg");
	this.shape_13.setTransform(11.1,17);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ10, new cjs.Rectangle(0,0,161.4,60.4), null);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABFBWIgNAAIgNAAIgGAAQgCAAgDgCIgFgHIgFgIIgJgNIgIgOIgEgGIgDAGIgIAOIgIANIgEAIIgFAHQgCACgEAAIgGAAIgOAAIgOAAIgIAAQgEgBgBgCQgCgCACgEIAHgJIANgTIAPgYIANgSIAFgHIgFgIIgLgTIgOgWIgMgTIgFgJQgCgDABgCQABgDAEABIAJAAIANAAIANAAIAFAAQAAAAABAAQABAAAAAAQABAAAAAAQABABAAAAIADAFIADAEIAGALIAHANIAGALIABADIACgDIAGgLIAHgNIAGgLIADgEIADgFQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAIAGAAIAMAAIANAAIAJAAQAEAAABABQACADgCADIgFAJIgMATIgNAWIgLATIgFAIIAFAHIANASIAOAYIANATIAGAJQACAEgBACQgCACgEABIgHAAg");
	this.shape.setTransform(150.5,42.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAfBWQAAAAgBgBQgBAAAAAAQgBAAAAgBQgBAAAAAAIgCgFIAAhQIgFAHIgMASIgOAWIgNAUIgHALQgEAFgDACQgDACgFAAIgcAAQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAAAIgCgFIAAidIACgFQAAAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAIAnAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAABIAABRIA2hRIAFgFQACgCAGABIAEAAIAJAAIAJAAIAFAAQAAAAABAAQAAAAABAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABAAABIAACdQAAABAAABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQgBABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_1.setTransform(132.3,42.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhoBWQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBAAAAAAIgCgFIAAidIACgFQAAAAABgBQABAAAAAAQABAAAAAAQABAAAAAAIAnAAQAAAAABAAQAAAAABAAQAAAAABAAQABABAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAABIAAB5IAjAAIAAh5QAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAABgBQAAAAABAAQAAAAABAAQAAAAABAAIAlAAQABAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAABAAAAQABABAAAAQAAABAAAAQABABAAABIAAB5IAjAAIAAh5QAAgBAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQABAAAAAAQABAAAAAAQABAAAAAAIAnAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAABIAACdQAAABAAABQAAAAAAABQgBAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAABgBAAg");
	this.shape_2.setTransform(111.2,42.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAcBWQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQgBgBAAgBIAAgxIgPACIgRABQgRABgOgFQgNgGgIgOQgJgNAAgZIAAgLIAAgRIAAgPIAAgGIABgFQABAAABgBQAAAAABAAQAAAAABAAQAAAAABAAIAmAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAABIAAAkIABARQABAIADAFQAEAFALAAQAGAAAFgCQAHAAAFgDIAAhCQAAgBABgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQABAAAAAAQABAAAAAAQABAAAAAAIAmAAQABAAABAAQABAAAAAAQABAAAAAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABABABIAACdQgBABAAABQAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAQgBABgBAAg");
	this.shape_3.setTransform(90.4,42.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag5BUQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBIAAgdQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQABgBAAAAQABAAABAAQAAgBABAAIAEAAIAKgBQAGgBAFgDQAFgDABgFIgKgWIgNgbIgNgbIgKgVIgEgJQgCgFABgCQABgBAEAAIAIAAIAMAAIAKAAIAEAAQAEgBACACIADAFIAFAKIAJAVIAMAbIALgdIAIgVIADgIIADgFQACgCAEABIAFAAIAKAAIAMAAIAIAAQAEAAABABQABACgCAEIgDAKIgJAUIgKAbIgLAaIgIAUIgFALQgIATgLAKQgLALgLADQgMAFgKAAIgPABQgBAAAAgBQgBAAgBAAQAAAAgBgBQAAAAgBAAg");
	this.shape_4.setTransform(73.4,42.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ABJBWIgOAAIgNAAIgGAAQgFAAgCgCQgCgCgCgFIgDgLIgHgWIgJgeIgKgfIgJAfIgJAeIgHAWIgEALQgBAFgCACQgCACgGAAIgFAAIgNAAIgOAAIgHAAQgEgBgBgCQgBgCABgEIAEgKIAIgXIALgeIALgfIALgeIAIgWIAEgJIADgFQABgCAEABIAnAAQAEgBABACIADAFIAEAJIAIAWIAKAeIAMAfIALAeIAIAXIADAKQACAEgBACQgCACgDABIgHAAg");
	this.shape_5.setTransform(55.1,42.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABKBWIgNAAIgNAAIgGAAQgFAAgCgCQgCgCgCgFIgCgFIgDgJIgzAAIgDAJIgCAFQgCAFgCACQgCACgFAAIgGAAIgNAAIgNAAIgIAAQgDgBgBgCQgCgCACgEIAEgKIAIgXIALgeIAMgfIALgeIAIgWIAEgJIADgFQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAIApAAQAAAAABAAQABAAAAAAQABAAAAAAQABABAAAAQACABABAEIAEAJIAIAWIALAeIAMAfIALAeIAJAXIADAKQACAEgCACQgBACgDABIgIAAgAANAVIgGgVIgHgTIgFATIgHAVIAZAAIAAAAg");
	this.shape_6.setTransform(27.9,42.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgdBTQgNgGgHgHQgIgIgDgHQgEgHAAgEQgCgIACgCQABgCAHAAIAMAAIANAAQADAAACACIADAEIAEAFQAEAEAGABIALABQAJAAAGgEQAGgEAAgKQAAgJgGgFQgGgEgNAAIgKAAIgFAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAgWQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAQABAAAAAAIACAAIAEAAQAMAAAGgEQAFgEAAgHQAAgGgEgDQgFgEgEAAQgGAAgEACQgFABgCAEQgBADgCABIgHABIgFAAIgJAAIgJAAQgFAAgCgCQgBgCAAgFQACgPAJgJQAJgJANgFQANgDANAAQAKAAAJACQAKACAIAFQAJAFAFAJQAFAIAAAMQAAAMgEAIQgFAIgEAEIgHAGIAAABQACAAAFADQAFACAFADQAGAFADAHQAEAHAAAKQAAAQgGALQgGALgKAHQgKAGgLADQgLACgKAAQgSAAgNgFg");
	this.shape_7.setTransform(10.1,42.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAfBuQAAAAgBAAQgBgBAAAAQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAhRIgFAHIgMASIgOAWIgNAUIgIALQgDAFgDACQgDACgFAAIgbAAQgBAAAAAAQgBgBgBAAQAAAAgBAAQAAgBgBAAIgCgEIAAieIACgFQABAAAAAAQABgBAAAAQABAAABAAQAAAAABAAIAmAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAQABABAAABQAAAAAAABIAABRIA2hRIAEgFQADgBAFAAIAFAAIAKAAIAIAAIAEAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABABAAQAAABAAAAQAAABABABQAAAAAAABIAACeQAAAAAAABQgBABAAAAQAAABAAAAQgBAAAAABQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAgAgehJQgBAAAAAAQgBAAgBAAQAAAAAAgBQgBAAAAAAQgBgBAAAAQAAgBgBAAQAAgBAAgBQAAAAAAgBIAAgXQAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAABgBQAAAAAAAAQABgBABAAQAAAAABAAIBEAAQAAAAABAAQAAAAABABQAAAAABAAQAAABABAAQAAABAAAAQABABAAAAQAAABAAAAQABABAAABIAAAXIgCAFQgBAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_8.setTransform(82.2,14.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag3BVQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAgBIgDgDIAAifIADgEQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAIBuAAQABAAABABQAAAAABAAQAAAAABAAQAAABABAAQAAAAABABQAAABAAAAQAAABAAAAQAAABAAAAIAAAeQAAABAAAAQAAABAAABQAAAAAAABQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAIhCAAIAAAXIA2AAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABIAAAdQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBABQAAAAgBAAQAAAAgBAAIg2AAIAAAXIBEAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAAAQABABAAAAQAAABAAAAQAAABAAAAIAAAfQAAAAAAABQAAAAAAABQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_9.setTransform(66,17);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ABJBVIgOAAIgNAAIgGAAQgFAAgCgCQgCgBgCgGIgDgKIgHgWIgJgeIgKgeIgJAeIgJAeIgHAWIgEAKQgBAGgCABQgCACgGAAIgFAAIgNAAIgOAAIgHAAQgEAAgBgCQgBgCABgEIAEgLIAIgWIALgeIALgfIALgeIAIgWIAEgKIADgEQABgCAEAAIAnAAQAEAAABACIADAEIAEAKIAIAWIAKAeIAMAfIALAeIAIAWIADALQACAEgBACQgCACgDAAIgHAAg");
	this.shape_10.setTransform(48.8,17);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgiBSQgRgIgMgLQgNgMgHgQQgHgRgBgSQABgSAHgPQAHgQANgMQAMgNARgGQAQgIASAAQATAAAQAIQARAGANANQAMAMAIAQQAHAPAAASQAAASgHARQgIAQgMAMQgNALgRAIQgQAGgTABQgSgBgQgGgAgVgmQgKAGgFAKQgGALAAALQAAANAGAJQAFALAKAGQAKAGALAAQAMAAAKgGQAKgGAGgLQAFgJAAgNQAAgLgFgLQgGgKgKgGQgKgGgMAAQgLAAgKAGg");
	this.shape_11.setTransform(28.6,17);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAABVIgQAAIgUAAIgRAAIgIAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQgBAAAAgBIgCgDIAAifIACgEQAAAAABgBQABAAAAAAQABAAAAAAQABgBAAAAIBnAAQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAABABAAQAAABAAAAQAAABAAAAIAAAeQAAABAAAAQAAABAAABQgBAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAIg6AAIAAAXIAQAAIAIAAQASAAANAFQAOAGAIALQAHALAAARQAAASgHANQgIAMgOAGQgNAHgSgBIgIAAgAgQAtIAMAAIAIAAQAHAAAFgEQAEgEAAgFQAAgGgEgDQgEgDgIgBIgHAAIgNAAg");
	this.shape_12.setTransform(10.2,17);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ9, new cjs.Rectangle(0,0,162.4,60.4), null);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.basket();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ7, new cjs.Rectangle(0,0,184,250), null);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.hokey();
	this.instance.parent = this;
	this.instance.setTransform(-29,0,1.156,1.156);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ6, new cjs.Rectangle(-29,0,335.3,324.9), null);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.t_shirts();
	this.instance.parent = this;
	this.instance.setTransform(-4,-2,1.141,1.141);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ5, new cjs.Rectangle(-4,-2,227.1,285.3), null);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.fonbet2gdfg();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ1, new cjs.Rectangle(0,0,760,400), null);


(lib.Символ42 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ43();
	this.instance.parent = this;
	this.instance.setTransform(472.4,267.2,1,1,0,0,0,472.4,267.2);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(214).to({alpha:0.293},10,cjs.Ease.quadInOut).to({alpha:0.379},5).wait(120).to({alpha:0},14,cjs.Ease.quadInOut).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,944.8,534.4);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 12
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AjFDwIAAnfIGLAAIAAHfg");
	this.shape.setTransform(-241.4,-114);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},229).wait(135));

	// Символ 36
	this.instance = new lib.Символ36();
	this.instance.parent = this;
	this.instance.setTransform(-91.1,140.1,0.728,0.728,0,0,0,43.1,30);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(257).to({_off:false},0).to({x:90.5,alpha:1},13,cjs.Ease.quadOut).wait(72).to({regY:30.2,scaleX:0.36,scaleY:0.36,y:140.2,alpha:0},8).wait(14));

	// Символ 37
	this.instance_1 = new lib.Символ37();
	this.instance_1.parent = this;
	this.instance_1.setTransform(60.3,135,0.728,0.728,0,0,0,41.6,37);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(251).to({_off:false},0).to({x:241.9,alpha:1},13,cjs.Ease.quadOut).wait(78).to({scaleX:0.44,scaleY:0.44,x:242,alpha:0},8).wait(14));

	// Символ 34
	this.instance_2 = new lib.Символ34();
	this.instance_2.parent = this;
	this.instance_2.setTransform(204.5,137.6,0.728,0.728,0,0,0,33,33.6);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(244).to({_off:false},0).to({x:386.1,alpha:1},13,cjs.Ease.quadOut).wait(85).to({scaleX:0.42,scaleY:0.42,alpha:0},8).wait(14));

	// Символ 35
	this.instance_3 = new lib.Символ35();
	this.instance_3.parent = this;
	this.instance_3.setTransform(338.8,139.7,0.728,0.728,0,0,0,28,30.5);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(236).to({_off:false},0).to({x:520.4,alpha:1},13,cjs.Ease.quadOut).wait(93).to({regX:28.2,regY:30.7,scaleX:0.5,scaleY:0.5,x:520.5,y:139.8,alpha:0},8).wait(14));

	// Символ 41
	this.instance_4 = new lib.Символ41();
	this.instance_4.parent = this;
	this.instance_4.setTransform(519.8,238.2,0.552,0.552,0,0,0,88.3,26.8);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(238).to({_off:false},0).to({y:190.2,alpha:1},13,cjs.Ease.backOut).wait(89).to({y:214.2,alpha:0},9,cjs.Ease.backIn).wait(15));

	// Символ 40
	this.instance_5 = new lib.Символ40();
	this.instance_5.parent = this;
	this.instance_5.setTransform(385,238.2,0.552,0.552,0,0,0,98.8,26.8);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(244).to({_off:false},0).to({y:190.2,alpha:1},13,cjs.Ease.backOut).wait(83).to({y:214.2,alpha:0},9,cjs.Ease.backIn).wait(15));

	// Символ 39
	this.instance_6 = new lib.Символ39();
	this.instance_6.parent = this;
	this.instance_6.setTransform(240.8,238.2,0.552,0.552,0,0,0,94.9,26.8);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(251).to({_off:false},0).to({y:190.2,alpha:1},13,cjs.Ease.backOut).wait(76).to({y:214.2,alpha:0},9,cjs.Ease.backIn).wait(15));

	// Символ 38
	this.instance_7 = new lib.Символ38();
	this.instance_7.parent = this;
	this.instance_7.setTransform(92.3,238.2,0.552,0.552,0,0,0,74.5,26.8);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(257).to({_off:false},0).to({y:190.2,alpha:1},13,cjs.Ease.backOut).wait(70).to({y:214.2,alpha:0},9,cjs.Ease.backIn).wait(15));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-261.2,-138,39.6,48);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ10();
	this.instance.parent = this;
	this.instance.setTransform(183.5,23.2,1.338,1.338,0,0,0,137.1,17.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(211).to({x:-84.5},15,cjs.Ease.backIn).wait(118).to({x:183.5},14,cjs.Ease.backOut).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,216,80.8);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ9();
	this.instance.parent = this;
	this.instance.setTransform(173,23.2,1.338,1.338,0,0,0,129.3,17.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(215).to({x:-103.8},14,cjs.Ease.backIn).wait(120).to({x:173},14,cjs.Ease.backOut).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,217.3,80.8);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ13();
	this.instance.parent = this;
	this.instance.setTransform(87,18.6,0.733,0.733,0,0,0,79.6,15.5);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D62A32").s().rr(-96.3,-21,192.6,42,3.5);
	this.shape.setTransform(87,19,0.904,0.904);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ26, new cjs.Rectangle(0,0,174.1,38), null);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ18();
	this.instance.parent = this;
	this.instance.setTransform(43.3,85.6,0.798,1.396,20.7,0,0,17,61.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:295.6},32).wait(55));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,86.7,171.3);


(lib.Символ17копия = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(4).call(this.frame_4).wait(1));

	// Слой 5
	this.instance = new lib.Символ25();
	this.instance.parent = this;
	this.instance.setTransform(87.1,19,0.931,0.931,0,0,0,93.3,20.3);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1,scaleY:1,y:18.9,alpha:1},4).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ26();
	this.instance_1.parent = this;
	this.instance_1.setTransform(87,19,1,1,0,0,0,87,19);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:1.07,scaleY:1.07,x:87.1,alpha:0},4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,174.1,38);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ13();
	this.instance.parent = this;
	this.instance.setTransform(87,18.6,0.733,0.733,0,0,0,79.6,15.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AtFi9IaMAAQAJAAAHAFQAHAEAEAHQAEAHAAAJIAAE7QAAAJgEAHQgEAHgHAFQgHAEgJAAI6MAAQgOAAgJgJQgJgJAAgOIAAk7QAAgJAEgHQAEgHAIgEQAHgFAJAAg");
	mask.setTransform(87,19);

	// Слой 4
	this.instance_1 = new lib.Символ19();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-41.9,12.7,1,1,0,0,0,43.4,85.6);
	this.instance_1.alpha = 0.59;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D62A32").s().rr(-96.3,-21,192.6,42,3.5);
	this.shape.setTransform(87,19,0.904,0.904);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ17, new cjs.Rectangle(0,0,174.1,38), null);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.ClipGroup();
	this.instance.parent = this;
	this.instance.setTransform(186.6,56.9,1,1,0,0,0,186.6,56.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ12, new cjs.Rectangle(0,0,373.2,113.8), null);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 7
	this.instance = new lib.Символ7();
	this.instance.parent = this;
	this.instance.setTransform(502.2,137.9,1.1,1.1,0,0,0,92,125);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(143).to({_off:false},0).to({x:146.6},14,cjs.Ease.backOut).wait(56).to({regX:92.1,scaleX:0.52,scaleY:0.52,x:145.8,y:139.3,alpha:0},15,cjs.Ease.backIn).to({_off:true},1).wait(135));

	// Символ 6
	this.instance_1 = new lib.Символ6();
	this.instance_1.parent = this;
	this.instance_1.setTransform(500.6,140.5,1,1,0,0,0,145,140.5);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(64).to({_off:false},0).to({x:145},14,cjs.Ease.backOut).wait(56).to({regY:140.6,scaleX:0.47,scaleY:0.47,y:140.6,alpha:0},15,cjs.Ease.backIn).to({_off:true},1).wait(214));

	// Символ 5
	this.instance_2 = new lib.Символ5();
	this.instance_2.parent = this;
	this.instance_2.setTransform(146,125,1,1,0,0,0,99.5,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(55).to({regY:125.1,scaleX:0.47,scaleY:0.47,x:145.5,y:133.3,alpha:0},15,cjs.Ease.backIn).to({_off:true},1).wait(278).to({_off:false,regY:125,scaleX:1,scaleY:1,x:501.6,y:125,alpha:1},0).to({x:146},14,cjs.Ease.backOut).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(42.5,-2,227.1,285.3);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ1();
	this.instance.parent = this;
	this.instance.setTransform(380,200,1,1,0,0,0,380,200);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ2, new cjs.Rectangle(0,0,760,400), null);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ12();
	this.instance.parent = this;
	this.instance.setTransform(66.6,20.3,0.357,0.357,0,0,0,186.7,57);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ32, new cjs.Rectangle(0,0,133.1,40.6), null);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ32();
	this.instance.parent = this;
	this.instance.setTransform(66.5,20.3,1,1,0,0,0,66.5,20.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(215).to({x:267.3},15,cjs.Ease.backInOut).wait(120).to({x:66.5},13,cjs.Ease.backInOut).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,133.1,40.6);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ8();
	this.instance.parent = this;
	this.instance.setTransform(73.8,102.3,0.717,0.717,0,0,0,145.3,140.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ29, new cjs.Rectangle(0,0,162.9,204.7), null);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ17();
	this.instance.parent = this;
	this.instance.setTransform(87,18.9,1,1,0,0,0,87,18.9);

	this.instance_1 = new lib.Символ17копия();
	this.instance_1.parent = this;
	this.instance_1.setTransform(87,18.9,1,1,0,0,0,87,18.9);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D62A32").s().rr(-96.3,-21,192.6,42,3.5);
	this.shape.setTransform(87,19,0.904,0.904);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance}]},1).to({state:[{t:this.shape}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-85.3,-72.9,259.4,171.3);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ2();
	this.instance.parent = this;
	this.instance.setTransform(380,200.1,1.116,1.116,0,0,0,379.9,200);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ16, new cjs.Rectangle(-43.9,-23.1,848,446.4), null);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ16();
	this.instance.parent = this;
	this.instance.setTransform(380,200,1,1,0,0,0,380,200);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:380.1,scaleX:0.87,scaleY:0.87,x:380.1,y:200.1},49,cjs.Ease.quadInOut).to({regX:380,scaleX:1,scaleY:1,x:380,y:200},51,cjs.Ease.quadInOut).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-43.9,-23.1,848,446.4);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ20();
	this.instance.parent = this;
	this.instance.setTransform(44.4,12.7,1,1,0,0,0,44.4,12.7);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.Символ20(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(214).to({x:-117.2},16,cjs.Ease.backInOut).wait(119).to({x:44.4},14,cjs.Ease.backInOut).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-85.3,-72.9,259.4,171.3);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ3();
	this.instance.parent = this;
	this.instance.setTransform(670.1,374.6,1,1,0,0,0,380,200);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ24, new cjs.Rectangle(246.2,151.5,848,446.4), null);


// stage content:
(lib.fb_600x300_tshirt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		stage.scaleX = stage.scaleY = 2;
		 stage.canvas.width = 600 * 2;
		 stage.canvas.height = 300 * 2;
		 stage.canvas.style.width = '600px';
		 stage.canvas.style.height = '300px';
		 
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
		
		this.addEventListener("tick", fl_CustomMouseCursor.bind(this));
		
		function fl_CustomMouseCursor() {
		
		this.fon.x = - stage.mouseX / 24;
		this.fon.y = - stage.mouseY / 18;
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой 6
	this.instance = new lib.Символ33();
	this.instance.parent = this;
	this.instance.setTransform(300,149.8,1,1,0,0,0,300,149.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 3
	this.instance_1 = new lib.Символ30();
	this.instance_1.parent = this;
	this.instance_1.setTransform(419.9,243.5,1,1,0,0,0,44.4,12.7);

	this.instance_2 = new lib.Символ29();
	this.instance_2.parent = this;
	this.instance_2.setTransform(470.3,121.6,1,1,0,0,0,81.4,102.3);

	this.instance_3 = new lib.Символ28();
	this.instance_3.parent = this;
	this.instance_3.setTransform(143.1,240.4,1,1,0,0,0,108,40.4);

	this.instance_4 = new lib.Символ27();
	this.instance_4.parent = this;
	this.instance_4.setTransform(143.7,142.1,1,1,0,0,0,108.6,40.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1}]}).wait(1));

	// Режим изоляции
	this.instance_5 = new lib.Символ31();
	this.instance_5.parent = this;
	this.instance_5.setTransform(100,49.5,1,1,0,0,0,66.5,20.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1));

	// Слой 7
	this.instance_6 = new lib.Символ42();
	this.instance_6.parent = this;
	this.instance_6.setTransform(326.8,144,1,1,0,0,0,472.4,267.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1));

	// Слой 1
	this.fon = new lib.Символ24();
	this.fon.parent = this;
	this.fon.setTransform(19.9,-27.5,1,1,0,0,0,380,200);

	this.timeline.addTween(cjs.Tween.get(this.fon).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(38.8,12,1060.4,549.2);
// library properties:
lib.properties = {
	id: '3691D1A67C9D264BA93D0F2063DD6720',
	width: 600,
	height: 300,
	fps: 27,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/basket.png?1506251879422", id:"basket"},
		{src:"images/fonbet2gdfg.jpg?1506251879422", id:"fonbet2gdfg"},
		{src:"images/hokey.png?1506251879422", id:"hokey"},
		{src:"images/incentive.png?1506251879422", id:"incentive"},
		{src:"images/stad.png?1506251879422", id:"stad"},
		{src:"images/stopwatch.png?1506251879422", id:"stopwatch"},
		{src:"images/t_shirts.png?1506251879422", id:"t_shirts"},
		{src:"images/time.png?1506251879422", id:"time"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['3691D1A67C9D264BA93D0F2063DD6720'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;